= Wise Words of Malcolm X

* Whites have always hidden or justified all of the guilts they could by ridiculing or blaming Negroes.

* This was my first lesson about gambling: if you see somebody winning all the time, he isn't gambling, he's cheating. Later on in life, if I were continuously losing in any gambling situation, I would watch very closely. It's like the Negro in America seeing the white man win all the time. He's a professional gambler; he has all the cards and the odds stacked on his side, and he has always dealt to our people from the bottom of the deck.

* All I had done was to improve on their strategy, and it was the beginning of a very important lesson in life—that anytime you find someone more successful than you are, especially when you're both engaged in the same business—you know they're doing something that you aren't.

* Eventually my mother suffered a complete breakdown, and the court orders were finally signed. They took her to the State Mental Hospital at Kalamazoo.  It was seventy-some miles from Lansing, about an hour and a half on the bus. A Judge McClellan in Lansing had authority over me and all of my brothers and sisters. We were "state children," court wards; he had the full say-so over us. A white man in charge of a black man's children! Nothing but legal, modern slavery—however kindly intentioned.

* I knew I wouldn't be back to see my mother again because it could make me a very vicious and dangerous person—knowing how they had looked at us as numbers and as a case in their book, not as human beings. And knowing that my mother in there was a statistic that didn't have to be, that existed because of a society's failure, hypocrisy, greed, and lack of mercy and compassion. Hence I have no mercy or compassion in me for a society that will crush people, and then penalize them for not being able to stand up under the weight.

* This is the sort of kindly condescension which I try to clarify today, to these integration-hungry Negroes, about their "liberal" white friends, these so-called "good white people"—most of them anyway. I don't care how nice one is to you; the thing you must always remember is that almost never does he really see you as he sees himself, as he sees his own kind. He may stand with you through thin, but not thick; when the chips are down, you'll find that as fixed in him as his bone structure is his sometimes subconscious conviction that he's better than anybody black.
