= Wise Words of Malcolm X

== The Autobiography of Malcolm X

* Whites have always hidden or justified all of the guilts they could by ridiculing or blaming Negroes.

* This was my first lesson about gambling: if you see somebody winning all the time, he isn't gambling, he's cheating. Later on in life, if I were continuously losing in any gambling situation, I would watch very closely. It's like the Negro in America seeing the white man win all the time. He's a professional gambler; he has all the cards and the odds stacked on his side, and he has always dealt to our people from the bottom of the deck.

* All I had done was to improve on their strategy, and it was the beginning of a very important lesson in life—that anytime you find someone more successful than you are, especially when you're both engaged in the same business—you know they're doing something that you aren't.

* Eventually my mother suffered a complete breakdown, and the court orders were finally signed. They took her to the State Mental Hospital at Kalamazoo.  It was seventy-some miles from Lansing, about an hour and a half on the bus. A Judge McClellan in Lansing had authority over me and all of my brothers and sisters. We were "state children," court wards; he had the full say-so over us. A white man in charge of a black man's children! Nothing but legal, modern slavery—however kindly intentioned.

* I knew I wouldn't be back to see my mother again because it could make me a very vicious and dangerous person—knowing how they had looked at us as numbers and as a case in their book, not as human beings. And knowing that my mother in there was a statistic that didn't have to be, that existed because of a society's failure, hypocrisy, greed, and lack of mercy and compassion. Hence I have no mercy or compassion in me for a society that will crush people, and then penalize them for not being able to stand up under the weight.

* This is the sort of kindly condescension which I try to clarify today, to these integration-hungry Negroes, about their "liberal" white friends, these so-called "good white people"—most of them anyway. I don't care how nice one is to you; the thing you must always remember is that almost never does he really see you as he sees himself, as he sees his own kind. He may stand with you through thin, but not thick; when the chips are down, you'll find that as fixed in him as his bone structure is his sometimes subconscious conviction that he's better than anybody black.

* This was my first really big step toward self-degradation: when I endured all of that pain, literally burning my flesh to have it look like a white man's hair. I had joined that multitude of Negro men and women in America who are brainwashed into believing that the black people are "inferior" and white people "superior"—that they will even violate and mutilate their God-created bodies to try to look "pretty" by white standards.

* Look around today, in every small town and big city, from two-bit catfish and soda-pop joints into the "integrated" lobby of the Waldorf-Astoria, and you'll see conks on black men. And you'll see black women wearing these green and pink and purple and red and platinum-blonde wigs. They're all more ridiculous than a slapstick comedy. It makes you wonder if the Negro has completely lost his sense of identity, lost touch with himself.

* Shorty would take me to groovy, frantic scenes in different chicks' and cats' pads, where with the lights and juke down mellow, everybody blew gage and juiced back and jumped. I met chicks who were fine as May wine, and cats who were hip to all happenings.

* Then, on the overnight layover, I naturally went sightseeing in downtown Washington. I was astounded to find in the nation's capital, just a few blocks from Capitol Hill, thousands of Negroes living worse than any I'd ever seen in the poorest sections of Roxbury; in dirt-floor shacks along unspeakably filthy lanes with names like Pig Alley and Goat Alley. I had seen a lot, but never such a dense concentration of stumblebums, pushers, hookers, public crap-shooters, even little kids running around at midnight begging for pennies, half-naked and barefooted. Some of the railroad cooks and waiters had told me to be very careful, because muggings, knifings and robberies went on every night among these Negroes...just a few blocks from the White House.

* I remember that once, when some passenger complaints had gotten me a warning, and I wanted to be careful, I was working down the aisle and a big, beefy, red-faced cracker soldier got up in front of me, so drunk he was weaving, and announced loud enough that everybody in the car heard him, "I'm going to fight you, nigger." I remember the tension. I laughed and told him, "Sure, I'll fight, but you've got too many clothes on." He had on a big Army overcoat. He took that off, and I kept laughing and said he still had on too many. I was able to keep that cracker stripping off clothes until he stood there drunk with nothing on from his pants up, and the whole car was laughing at him, and some other soldiers got him out of the way. I went on. I never would forget that—that I couldn't have whipped that white man as badly with a club as I had with my mind.

* Many times since, I have thought about it, and what it really meant. In one sense, we were huddled in there, bonded together in seeking security and warmth and comfort from each other, and we didn't know it. All of us—who might have probed space, or cured cancer, or built industries—were, instead, black victims of the white man's American social system.

* Then there was the burglar, "Jumpsteady." In the ghettoes the white man has built for us, he has forced us not to aspire to greater things, but to view everyday living as survival—and in that kind of a community, survival is what is respected. In any average white neighborhood bar, you couldn't imagine a known cat-man thief regularly exposing himself, as one of the most popular people in there. But if Jumpsteady missed a few days running in Small's, we would begin inquiring for him.

* I got my first schooling about the cesspool morals of the white man from the best possible source, from his own women. And then as I got deeper into my own life of evil, I saw the white man's morals with my own eyes. I even made my living helping to guide him to the sick things he wanted.

* most white men's hearts and guts will turn over inside of them, whatever they may have you otherwise believe, whenever they see a Negro man on close terms with a white woman.


* Sammy said that white women were very practical; he had heard so many of them express how they felt. They knew that the black man had all the strikes against him, that the white man kept the black man down, under his heel, unable to get anywhere, really. The white woman wanted to be comfortable, she wanted to be looked upon with favor by her own kind, but also she wanted to have her pleasure. So some of them just married a white man for convenience and security, and kept right on going with a Negro. It wasn't that they were necessarily in love with the Negro, but they were in love with lust—particularly "taboo" lust.  A white man was not too unusual if he had a ten-, twenty-, thirty-, forty-, or fifty-thousand-dollar a-year job. A Negro man who made even five thousand in the white man's world was unusual. The white woman with a Negro man would be with him for one of two reasons: either extremely insane love, or to satisfy her lust.

* this was the worst of the ghetto, the poorest people, the ones who in every ghetto keep themselves narcotized to keep from having to face their miserable existence. I didn't last long down there, either. I lost too much of my product. After I sold to some of those reefer smokers who had the instincts of animals, they followed meand learned my pattern. They would dart out of a doorway, I'd drop my stuff, and they would be on it like a chicken on corn. When you become an animal, a vulture, in the ghetto, as I had become, you enter a world of animals and vultures. It becomes truly the survival of only the fittest.

* Most whites don't give a Negro credit for having sense enough to fool them—or nerve enough.

* In those days only three things in the world scared me: jail, a job, and the Army. I had about ten days before I was to show up at the induction center. I went right to work. The Army Intelligence soldiers, those black spies in civilian clothes, hung around in Harlem with their ears open for the white man downtown. I knew exactly where to start dropping the word. I started noising aroundthat I was frantic to join...the Japanese Army.

* So many of those so-called "upper class" Negroes are so busy trying to impress on the white man that they are "different from those others" that they can't see they are only helping the white man to keep his low opinion of all Negroes.

* Suddenly, I sprang up and peeped under both doors, the one I'd entered and another that probably was a closet. And then I bent and whispered fast in his ear. "Daddy-o, now you and me, we're from up North here, so don't you tell nobody....I want to get sent down South. Organize them nigger soldiers, you dig? Steal us some guns, and kill us crackers!"  That psychiatrist's blue pencil dropped, and his professional manner fell off in all directions. He stared at me as if I were a snake's egg hatching, fumbling for his red pencil. I knew I had him. I was going back out past Miss First when he said, "That will be all."  A 4-F card came to me in the mail, and I never heard from the Army any more, and never bothered to ask why I was rejected.

* There I was back in Harlem's streets among all the rest of the hustlers. I couldn't sell reefers; the dope squad detectives were too familiar with me. I was a true hustler—uneducated, unskilled at anything honorable, and I considered myself nervy and cunning enough to live by my wits, exploiting any prey that presented itself. I would risk just about anything.

* Right now, in every big city ghetto, tens of thousands of yesterday's and today's school drop-outs are keeping body and soul together by some form of hustling in the same way I did. And they inevitably move into more and more, worse and worse, illegality and immorality. Full-time hustlers never can relax to appraise what they are doing and where they are bound. As is the case in any jungle, the hustler's every waking hour is lived with both the practical and the subconscious knowledge that if he ever relaxes, if he ever slows down, the other hungry, restless foxes, ferrets, wolves, and vultures out there with him won't hesitate to make him their prey.

* Between jobs, staying high on narcotics kept me from getting nervous.

* Once on a job with Sammy, we had a pretty close call. Someone must have seen us. We were making our getaway, running, when we heard the sirens. Instantly, we slowed to walking. As a police car screeched to a stop, we stepped out into the street, meeting it, hailing it to ask for directions. They must have thought we were about to give them some information. They just cursed us and raced on. Again, it didn't cross the white men's minds that a trick like that might be pulled on them by Negroes.

* That was just another example of why my respect for my younger brother kept increasing. Reginald showed, in often surprising ways, more sense than a lot of working hustlers twice his age. Reginald then was only sixteen, but, a six-footer, he looked and acted much older than his years.

* And we laughed about the scared little Chinese whose restaurant didn't have a hand laid on it, because the rioters just about convulsed laughing when they saw the sign the Chinese had hastily stuck on his front door: "Me Colored Too."

* She knew from personal experience how crime existed only to the degree that the law cooperated with it. She showed me how, in the country's entire social, political and economic structure, the criminal, the law, and the politicians were actually inseparable partners.

* I've often reflected upon such black veteran numbers men as West Indian Archie. If they had lived in another kind of society, their exceptional mathematical talents might have been better used. But they were black.

* A Harlem madam I'd come to know—through having done a friend of hers a favor—introduced me to a special facet of the Harlem night world, something which the riot had only interrupted. It was the world where, behind locked doors, Negroes catered to monied white people's weird sexual tastes.

* Rich men, middle-aged and beyond, men well past their prime: these weren't college boys, these were their Ivy League fathers. Even grandfathers, I guess. Society leaders. Big politicians. Tycoons. Important friends from out of town. City government big shots. All kinds of professional people. Star performing artists. Theatrical and Hollywood celebrities. And, of course, racketeers.  Harlem was their sin-den, their fleshpot. They stole off among taboo black people, and took off whatever antiseptic, important, dignified masks they wore in their white world. These were men who could afford to spend large amounts of money for two, three, or four hours indulging their strange appetites.But in this black-white nether world, nobody judged the customers. Anything they could name, anything they could imagine, anything they could describe, they could do, or could have done to them, just as long as they paid.

* One of my main steers to one specialty address away from the madam's house was the apartment of a big, coal-black girl, strong as an ox, with muscles like a dockworker's. A funny thing, it generally was the oldest of these white men—in their sixties, I know, some maybe in their seventies—they couldn't seem to recover quickly enough from their last whipping so they could have me meet them again at 45th and Broadway to take them back to that apartment, to cringe on their knees and beg and cry out for mercy under that black girl's whip. Some of them would pay me extra to come and watch them being beaten. That girl greased her big Amazon body all over to look shinier and blacker. She used small, plaited whips, she would draw blood, and she was making herself a small fortune off those old white men.  I wouldn't tell all the things I've seen. I used to wonder, later on, when I was in prison, what a psychiatrist would make of it all. And so many of these men held responsible positions; they exercised guidance, influence, and authority over others.  In prison later, I'd think, too, about another thing. Just about all of those whites specifically expressed as their preference black, black, "the blacker the better!" The madam, having long since learned this, had in her house nothing but the blackest accommodating women she could find.

* This Lesbian, a beautiful white woman, had a male Negro stable. Her vocabulary was all profanity. She supplied Negro males, on order, to well-to-do white women.

* white society never thinks about challenging any Negro in a servant role.

* The irony is that those white women had no more respect for those Negroes than white men have had for the Negro women they have been "using" since slavery times. And, in turn, Negroes have no respect for the whites they get into bed with.

* The hypocritical white man will talk about the Negro's "low morals." But who has the world's lowest morals if not whites? And not only that, but the "upper-class" whites! Recently, details were published about a group of suburban New York City white housewives and mothers operating as a professional call-girl ring. In some cases, these wives were out prostituting with the agreement, even the cooperation, of husbands, some of whom even waited at home, attending the children. And the customers—to quote a major New York City morning newspaper: "Some 16 ledgers and books with names of 200 Johns, many important social, financial and political figures, were seized in the raid Friday night."

* I have also read recently about groups of young white couples who get together, the husbands throw their house keys into a hat, then, blindfolded, the husbands draw out a key and spend the night with the wife that the house key matches. I have never heard of anything like that beingdone by Negroes, even Negroes who live in the worst ghettoes and alleys and gutters.

* s. Like most bars in Harlem, Negroes fronted, and a Jew really owned the place. To get a license, one had to know somebody in the State Liquor Authority, and Jews working with Jews seemed to have the best S.L.A. contacts.

* It was at about this time, too, I remember, that I began to be sick. I had colds all the time. It got to be a steady irritation, always sniffling and wiping my nose, all day, all night. I stayed so high that I was in a dream world. Now, sometimes, I smoked opium with some white friends, actors who lived downtown. And I smoked more reefers than ever before. I didn't smoke the usual wooden-match-sized sticks of marijuana. I was so far gone by now that I smoked it almost by the ounce.

* Hymie really liked me, and I liked him. He loved to talk. I loved to listen. Half his talk was about Jews and Negroes. Jews who had anglicized their names were Hymie's favorite hate. Spitting and curling his mouth in scorn, he would reel off names of people he said had done this. Some of them were famous names whom most people never thought of as Jews.  "Red, I'm a Jew and you're black," he would say. "These Gentiles don't like either one of us. If the Jew wasn't smarter than the Gentile, he'd get treated worse than your people."

* Sometimes, recalling all of this, I don't know, to tell the truth, how I am alive to tell it today. They say God takes care of fools and babies. I've so often thought that Allah was watching over me. Through all of this time of my life, I really was dead—mentally dead. I just didn't know that I was.

* Ella couldn't believe how atheist, how uncouth I had become. I believed that a man should do anything that he was slick enough, or bad and bold enough, to do and that a woman was nothing but another commodity. Every word I spoke was hip or profane. I would bet that my working vocabulary wasn't two hundred words.  Even Shorty, whose apartment I now again shared, wasn't prepared for how I lived and though —like a predatory animal. Sometimes I would catch him watching me.

* I showed my hole card ace; John had three queens. As I hauled in the pot, something over five hundred dollars—my first real stake in Boston—John got up from the table. He'd quit. He told his house man, "Anytime Red comes in here and wants anything, let him have it." He said, "I've never seen a young man play his hole card like he played."

* John had a standing rule that anyone who came into the place to gamble had to check his guns if he had any. I always checked two guns. Then, one night, when a gambler tried to pull something slick, I drew a third gun, from its shoulder holster. This added to the rest of my reputation the word that I was "trigger-happy" and "crazy."  Looking back, I think I really was at least slightly out of my mind. I viewed narcotics as most people regard food. I wore my guns as today I wear my neckties. Deep down, I actually believed that after living as fully as humanly possible, one should then die violently. I expected then, as I still expect today, to die at any time. But then, I think I deliberately invited death in many, sometimes insane, ways.

* All of a sudden, I pulled out my gun, shook out all five bullets, and then let them see me put back only one bullet. I twirled the cylinder, and put the muzzle to my head.  "Now, I'm going to see how much guts all of you have," I said.  I grinned at them. All of their mouths had flapped open. I pulled the trigger—we all heard it click.  "I'm going to do it again, now."  They begged me to stop. I could see in Shorty's and Rudy's eyes some idea of rushing me.  We all heard the hammer click on another empty cylinder.  The women were in hysterics. Rudy and Shorty were begging, "Man...Red...cut it out, man! Freeze!" I pulled the trigger once more.  "I'm doing this, showing you I'm not afraid to die," I told them. "Never cross a man not afraid todie...now, let's get to work!"  I never had one moment's trouble with any of them after that. Sophia acted awed, her sister all but called me "Mr. Red." Shorty and Rudy were never again quite the same with me. Neither of them ever mentioned it. They thought I was crazy. They were afraid of me.

* Every burglarknew that fences robbed the burglars worse than the burglars had robbed the victims.

* But I knew that the white man is rare who will ever consider that a Negro can outsmart him. Before their light began flashing, I told Rudy to stop. I did what I'd done once before—got out and flagged them, walking toward them. When they stopped, I was at their car. I asked them, bumbling my words like a confused Negro, if they could tell me how to get to a Roxbury address. They told me, and we, and they, went on about our respective businesses.

* There I was, wearing my gun, and the detective talking to that Negro with his back to me. Today I believe that Allah was with me even then. I didn't try to shoot him. And that saved my life.  I remember that his name was Detective Slack.  I raised my arm, and motioned to him, "Here, take my gun."  I saw his face when he took it. He was shocked. Because of the sudden appearance of the other Negro, he had never thought about a gun. It really moved him that I hadn't tried to kill him.

* I have thought a thousand times, I guess, about how I so narrowly escaped death twice that day. That's why I believe that everything is written.

* The social workers worked on us. White women in league with Negroes was their main obsession. The girls weren't so-called "tramps," or "trash," they were well-to-do upper-middle class whites. That bothered the social workers and the forces of the law more than anything else.  How, where, when, had I met them? Did we sleep together? Nobody wanted to know anything at all about the robberies. All they could see was that we had taken the white man's women.  I just looked at the social workers: "Now, what do you think?"  Even the court clerks and the bailiffs: "Nice white girls...goddam niggers—" It was the same even from our court-appointed lawyers as we sat down, under guard, at a table, as our hearing assembled. Before the judge entered, I said to one lawyer, "We seem to be getting sentenced because of those girls." He got red from the neck up and shuffled his papers: "You had no business with white girls!"  Later, when I had learned the full truth about the white man, I reflected many times that the average burglary sentence for a first offender, as we all were, was about two years. But we weren't going to get the average—not for our crime.

* I am spending many hours because the full story is the best way that I know to have it seen, and understood, that I had sunk to the very bottom of the American white man's society when—soon now, in prison—I found Allah and the religion of Islam and it completely transformed my life.

* Any person who claims to have deep feeling for other human beings should think a long, long time before he votes to have other men kept behind bars—caged. I am not saying there shouldn't be prisons, but there shouldn't be bars. Behind bars, a man never reforms. He willnever forget. He never will get completely over the memory of the bars.  After he gets out, his mind tries to erase the experience, but he can't. I've talked with numerous former convicts. It has been very interesting to me to find that all of our minds had blotted away many details of years in prison. But in every case, he will tell you that he can't forget those bars.

* As a "fish" (prison slang for a new inmate) at Charlestown, I was physically miserable and as evil tempered as a snake, being suddenly without drugs. The cells didn't have running water. The prison had been built in 1805—in Napoleon's day—and was even styled after the Bastille. In the dirty, cramped cell, I could lie on my cot and touch both walls. The toilet was a covered pail; I don't care how strong you are, you can't stand having to smell a whole cell row of defecation.

* I preferred the solitary that this behavior brought me. I would pace for hours like a caged leopard, viciously cursing aloud to myself. And my favorite targets were the Bible and God. But there was a legal limit to how much time one could be kept in solitary. Eventually, the men in the cellblock had a name for me: "Satan." Because of my antireligious attitude.

* Bimbi seldom said much to me; he was gruff to individuals, but I sensed he liked me. What made me seek his friendship was when I heard him discuss religion. I considered myself beyond atheism—I was Satan. But Bimbi put the atheist philosophy in a framework, so to speak. That ended my vicious cursing attacks. My approach sounded so weak alongside his, and he never used a foul word.

* It made me very proud, in some odd way. One of the universal images of the Negro, in prison and out, was that he couldn't do without pork. It made me feel good to see that my not eating it had especially startled the white convicts.  Later I would learn, when I had read and studied Islam a good deal, that, unconsciously, my first pre-Islamic submission had been manifested. I had experienced, for the first time, the Muslim teaching, "If you will take one step toward Allah—Allah will take two steps toward you."

* A celebrity among the Norfolk Prison Colony inmates was a rich, older fellow, a paralytic, called John. He had killed his baby, one of those "mercy" killings. He was a proud, big-shot type, always reminding everyone that he was a 33rd-degree Mason, and what powers Masons had—that only Masons ever had been U. S. Presidents, that Masons in distress could secretly signal to judges and other Masons in powerful positions.

* When Reginald left, he left me rocking with some of the first serious thoughts I had ever had in my life: that the white man was fast losing his power to oppress and exploit the dark world; that the dark world was starting to rise to rule the world again, as it had before; that the white man's world was on the way down, it was on the way out.

* Human history's greatest crime was the traffic in black flesh when the devil white man went into Africa and murdered and kidnapped to bring to the West in chains, in slave ships, millions of black men, women, and children, who were worked and beaten and tortured as slaves.  The devil white man cut these black people off from all knowledge of their own kind, and cut them off from any knowledge of their own language, religion, and past culture, until the black man in America was the earth's only race of people who had absolutely no knowledge of his true identity.  In one generation, the black slave women in America had been raped by the slavemaster white man until there had begun to emerge a homemade, handmade, brainwashed race that was no longer even of its true color, that no longer even knew its true family names. The slavemaster forced his family name upon this rape-mixed race, which the slavemaster began to call "the Negro."  This "Negro" was taught of his native Africa that it was peopled by heathen, black savages, swinging like monkeys from trees. This "Negro" accepted this along with every other teaching ofthe slavemaster that was designed to make him accept and obey and worship the white man.

* And where the religion of every other people on earth taught its believers of a God with whom they could identify, a God who at least looked like one of their own kind, the slavemaster injected his Christian religion into this "Negro." This "Negro" was taught to worship an alien God having the same blond hair, pale skin, and blue eyes as the slavemaster.  This religion taught the "Negro" that black was a curse. It taught him to hate everything black, including himself. It taught him that everything white was good, to be admired, respected, and loved. It brainwashed this "Negro" to think he was superior if his complexion showed more of the white pollution of the slavemaster. This white man's Christian religion further deceived and brainwashed this "Negro" to always turn the other cheek, and grin, and scrape, and bow, and be humble, and to sing, and to pray, and to take whatever was dished out by the devilish white man; and to look for his pie in the sky, and for his heaven in the hereafter, while right here on earth the slavemaster white man enjoyed his heaven.

* I have since learned—helping me to understand what then began to happen within me—that the truth can be quickly received, or received at all, only by the sinner who knows and admits that he is guilty of having sinned much. Stated another way: only guilt admitted accepts truth. The Bible again: the one people whom Jesus could not help were the Pharisees; they didn't feel they needed any help.  The very enormity of my previous life's guilt prepared me to accept the truth.  Not for weeks yet would I deal with the direct, personal application to myself, as a black man, of the truth. It still was like a blinding light.

* I was to learn later that Elijah Muhammad's tales, like this one of "Yacub," infuriated the Muslims of the East. While at Mecca, I reminded them that it was their fault, since they themselves hadn't done enough to make real Islam known in the West. Their silence left a vacuum into which any religious faker could step and mislead our people.

* The hardest test I ever faced in my life was praying. You understand. My comprehending, my believing the teachings of Mr. Muhammad had only required my mind's saying to me, "That's right!" or "I never thought of that."  But bending my knees to pray—that act—well, that took me a week.  You know what my life had been. Picking a lock to rob someone's house was the only way my knees had ever been bent before.  I had to force myself to bend my knees. And waves of shame and embarrassment would force me back up.  For evil to bend its knees, admitting its guilt, to implore the forgiveness of God, is the hardest thing in the world. It's easy for me to see and to say that now. But then, when I was the personification of evil, I was going through it. Again, again, I would force myself back down into the praying-to-Allah posture. When finally I was able to make myself stay down—I didn't know what to say to Allah.

* The teachings of Mr. Muhammad stressed how history had been "whitened"—when white men had written history books, the black man simply had been left out. Mr. Muhammad couldn't have said anything that would have struck me much harder. I had never forgotten how when my class, me and all of those whites, had studied seventh-grade United States history back in Mason, the history of the Negro had been covered in one paragraph, and the teacher had gotten a big laugh with his joke, "Negroes' feet are so big that when they walk, they leave a hole in the ground."  This is one reason why Mr. Muhammad's teachings spread so swiftly all over the United States, among all Negroes, whether or not they became followers of Mr. Muhammad. The teachings ring true—to every Negro. You can hardly show me a black adult in America—or a white one, for that matter—who knows from the history books anything like the truth about the black man's role. In my own case, once I heard of the "glorious history of the black man," I took special pains to hunt in the library for books that would inform me on details about black history.

* I never will forget how shocked I was when I began reading about slavery's total horror. It madesuch an impact upon me that it later became one of my favorite subjects when I became a minister of Mr. Muhammad's. The world's most monstrous crime, the sin and the blood on the white man's hands, are almost impossible to believe. Books like the one by Frederick Olmstead opened my eyes to the horrors suffered when the slave was landed in the United States. The European woman, Fannie Kimball, who had married a Southern white slaveowner, described how human beings were degraded. Of course I read Uncle Tom's Cabin. In fact, I believe that's the only novel I have ever read since I started serious reading.

* Parkhurst's collection also contained some bound pamphlets of the Abolitionist Anti-Slavery Society of New England. I read descriptions of atrocities, saw those illustrations of black slave women tied up and flogged with whips; of black mothers watching their babies being dragged off, never to be seen by their mothers again; of dogs after slaves, and of the fugitive slave catchers, evil white men with whips and clubs and chains and guns. I read about the slave preacher Nat Turner, who put the fear of God into the white slavemaster. Nat Turner wasn't going around preaching pie-in-the-sky and "non-violent" freedom for the black man. There in Virginia one night in 1831, Nat and seven other slaves started out at his master's home and through the night they went from one plantation "big house" to the next, killing, until by the next morning 57 white people were dead and Nat had about 70 slaves following him. White people, terrified for their lives, fled from their homes, locked themselves up in public buildings, hid in the woods, and some even left the state. A small army of soldiers took two months to catch and hang Nat Turner. Somewhere I have read where Nat Turner's example is said to have inspired John Brown to invade Virginia and attack Harper's Ferry nearly thirty years later, with thirteen white men and five Negroes.

* I read Herodotus, "the father of History," or, rather, I read about him. And I read the histories of various nations, which opened my eyes gradually, then wider and wider, to how the whole world's white men had indeed acted like devils, pillaging and raping and bleeding and draining the whole world's non-white people. I remember, for instance, books such as Will Durant's story of Oriental civilization, and Mahatma Gandhi's accounts of the struggle to drive the British out of India.  Book after book showed me how the white man had brought upon the world's black, brown, red, and yellow peoples every variety of the sufferings of exploitation. I saw how since the sixteenth century, the so-called "Christian trader" white man began to ply the seas in his lust for Asian and African empires, and plunder, and power. I read, I saw, how the white man never has gone among the non-white peoples bearing the Cross in the true manner and spirit of Christ's teachings—meek, humble, and Christ-like.  I perceived, as I read, how the collective white man had been actually nothing but a piratical opportunist who used Faustian machinations to make his own Christianity his initial wedge in criminal conquests. First, always "religiously," he branded "heathen" and "pagan" labels upon ancient non-white cultures and civilizations. The stage thus set, he then turned upon his non white victims his weapons of war.

* I read how, entering India—half a billion deeply religious brown people—the British white man,by 1759, through promises, trickery and manipulations, controlled much of India through Great Britain's East India Company. The parasitical British administration kept tentacling out to half of the subcontinent. In 1857, some of the desperate people of India finally mutinied—and, excepting the African slave trade, nowhere has history recorded any more unnecessary bestial and ruthless human carnage than the British suppression of the non-white Indian people.  Over 115 million African blacks—close to the 1930's population of the United States—were murdered or enslaved during the slave trade. And I read how when the slave market was glutted, the cannibalistic white powers of Europe next carved up, as their colonies, the richest areas of the black continent. And Europe's chancelleries for the next century played a chess game of naked exploitation and power from Cape Horn to Cairo.

* Ten guards and the warden couldn't have torn me out of those books. Not even Elijah Muhammad could have been more eloquent than those books were in providing indisputable proof that the collective white man had acted like a devil in virtually every contact he had with the world's collective non-white man. I listen today to the radio, and watch television, and read the headlines about the collective white man's fear and tension concerning China. When the white man professes ignorance about why the Chinese hate him so, my mind can't help flashing back to what I read, there in prison, about how the blood forebears of this same white man raped China at a time when China was trusting and helpless. Those original white "Christian traders" sent into China millions of pounds of opium. By 1839, so many of the Chinese were addicts that China's desperate government destroyed twenty thousand chests of opium. The first Opium War was promptly declared by the white man. Imagine! Declaring war upon someone who objects to being narcotized! The Chinese were severely beaten, with Chinese-invented gunpowder.

* Let us face reality. We can see in the United Nations a new world order being shaped, along color lines—an alliance among the non-white nations. America's U.N. Ambassador Adlai Stevenson complained not long ago that in the United Nations "a skin game" was being played. He was right. He was facing reality. A "skin game" is being played. But Ambassador Stevenson sounded like Jesse James accusing the marshal of carrying a gun. Because who in the world's history ever has played a worse "skin game" than the white man?

* You will never catch me with a free fifteen minutes in which I'm not studying something I feel might be able to help the black man.

* Yesterday I spoke in London, and both ways on the plane across the Atlantic I was studying a document about how the United Nations proposes to insure the human rights of the oppressed minorities of the world. The American black man is the world's most shameful case of minority oppression. What makes the black man think of himself as only an internal United States issue is just a catch-phrase, two words, "civil rights." How is the black man going to get "civil rights" before first he wins his human rights? If the American black man will start thinking about his human rights, and then start thinking of himself as part of one of the world's great peoples, he will see he has a case for the United Nations.

* I'll tell you something. The whole stream of Western philosophy has now wound up in a cul-de sac. The white man has perpetrated upon himself, as well as upon the black man, so gigantic a fraud that he has put himself into a crack. He did it through his elaborate, neurotic necessity to hide the black man's true role in history.

* It's a crime, the lie that has been told to generations of black men and white men both. Little innocent black children, born of parents who believed that their race had no history. Little black children seeing, before they could talk, that their parents considered themselves inferior. Innocent black children growing up, living out their lives, dying of old age—and all of their lives ashamed of being black. But the truth is pouring out of the bag now.

* I began first telling my black brother inmates about the glorious history of the black man things they never had dreamed. I told them the horrible slavery-trade truths that they never knew. I would watch their faces when I told them about that, because the white man had completely erased the slaves' past, a Negro in America can never know his true family name, or even what tribe he was descended from: the Mandingos, the Wolof, the Serer, the Fula, the Fanti, the Ashanti, or others. I told them that some slaves brought from Africa spoke Arabic, and were Islamic in their religion. A lot of these black convicts still wouldn't believe it unless they could see that a white man had said it. So, often, I would read to these brothers selected passages from white men's books. I'd explain to them that the real truth was known to some white men, the scholars; but there had been a conspiracy down through the generations to keep the truth from black men.

* You let this caged-up black man start thinking, the same way I did when I first heard Elijah Muhammad's teachings: let him start thinking how, with better breaks when he was young and ambitious he might have been a lawyer, a doctor, a scientist, anything. You let this caged-up black man start realizing, as I did, how from the first landing of the first slave ship, the millions of black men in America have been like sheep in a den of wolves. That's why black prisoners become Muslims so fast when Elijah Muhammad's teachings filter into their cages by way of other Muslim convicts. "The white man is the devil" is a perfect echo of that black convict's lifelong experience.

* "Compulsory Military Training—Or None?" That's one good chance I got unexpectedly, I remember. My opponent flailed the air about the Ethiopians throwing rocks and spears at Italian airplanes, "proving" that compulsory military training was needed. I said the Ethiopians' black flesh had been spattered against trees by bombs the Pope in Rome had blessed, and the Ethiopians would have thrown even their bare bodies at the airplanes because they had seen that they were fighting the devil incarnate.  They yelled "foul," that I'd made the subject a race issue. I said it wasn't race, it was a historical fact, that they ought to go and read Pierre van Paassen's Days of Our Years, and something not surprising to me, that book, right after the debate, disappeared from the prison library. It was right there in prison that I made up my mind to devote the rest of my life to telling the white man about himself—or die. In a debate about whether or not Homer had ever existed, I threw into those white faces the theory that Homer only symbolized how white Europeans kidnapped black Africans, then blinded them so that they could never get back to their own people. (Homer and Omar and Moor, you see, are related terms; it's like saying Peter, Pedro, and petra, all three of which mean rock.) These blinded Moors the Europeans taught to sing about the Europeans' glorious accomplishments. I made it clear that was the devilish white man's idea of kicks. Aesop's Fables—another case in point. "Aesop" was only the Greek name for an Ethiopian.

* It was the next night, as I lay on my bed, I suddenly, with a start, became aware of a man sitting beside me in my chair. He had on a dark suit. I remember. I could see him as plainly as I see anyone I look at. He wasn't black, and he wasn't white. He was light-brown-skinned, an Asiatic cast of countenance, and he had oily black hair.  I looked right into his face.  I didn't get frightened. I knew I wasn't dreaming. I couldn't move, I didn't speak, and he didn't. I couldn't place him racially—other than that I knew he was a non-European. I had no ideawhatsoever who he was. He just sat there. Then, suddenly as he had come, he was gone.

* One letter, I think from my brother Philbert, told me that Reginald was with them in Detroit. I heard no more about Reginald until one day, weeks later, Ella visited me; she told me that Reginald was at her home in Roxbury, sleeping. Ella said she had heard a knock, she had gone to the door, and there was Reginald, looking terrible. Ella said she had asked, "Where did you come from?" And Reginald had told her he came from Detroit. She said she asked him, "How did you get here?" And he had told her, "I walked."

* He next began to believe that he was the "Messenger of Allah." Reginald went around in the streets of Roxbury, Ella reported to me, telling people that he had some divine power. He graduated from this to saying that he was Allah.  He finally began saying he was greater than Allah.  Authorities picked up Reginald, and he was put into an institution. They couldn't find what was wrong. They had no way to understand Allah's chastisement. Reginald was released. Then he was picked up again, and was put into another institution.  Reginald is in an institution now. I know where, but I won't say. I would not want to cause him any more trouble than he has already had.  I believe, today, that it was written, it was meant, for Reginald to be used for one purpose only: as a bait, as a minnow to reach into the ocean of blackness where I was, to save me.  I cannot understand it any other way.  After Elijah Muhammad himself was later accused as a very immoral man, I came to believe that it wasn't a divine chastisement upon Reginald, but the pain he felt when his own family totally rejected him for Elijah Muhammad, and this hurt made Reginald turn insanely upon Elijah Muhammad.

* Conducting the class was a tall, blond, blue-eyed (a perfect "devil") Harvard Seminary student. He lectured, and then he started in a question-and-answer session. I don't know which of us had read the Bible more, he or I, but I had to give him credit; he really was heavy on his religion. I puzzled and puzzled for a way to upset him, and to give those Negroes present something to think and talk about and circulate.  Finally, I put up my hand; he nodded. He had talked about Paul.  I stood up and asked, "What color was Paul?" And I kept talking, with pauses, "He had to be black...because he was a Hebrew...and the original Hebrews were black...weren't they?"  He had started flushing red. You know the way white people do. He said "Yes."  I wasn't through yet. "What color was Jesus...he was Hebrew, too...wasn't he?"  Both the Negro and the white convicts had sat bolt upright. I don't care how tough the convict, be he brainwashed black Christian, or a "devil" white Christian, neither of them is ready to hear anybody saying Jesus wasn't white. The instructor walked around. He shouldn't have felt bad. In all of the years since, I never have met any intelligent white man who would try to insist that Jesus was white. How could they? He said, "Jesus was brown."  I let him get away with that compromise.

* The furniture store that my brother Wilfred managed was right in the black ghetto of Detroit; I'd better not name the store, if I'm going to tell the way they robbed Negroes. Wilfred introduced me to the Jews who owned the store. And, as agreed, I was put to work, as a salesman.  "Nothing Down" advertisements drew poor Negroes into that store like flypaper. It was a shame, the way they paid three and four times what the furniture had cost, because they could get credit from those Jews. It was the same kind of cheap, gaudy-looking junk that you can see in any of the black ghetto furniture stores today. Fabrics were stapled on the sofas. Imitation "leopard skin" bedspreads, "tiger skin" rugs, such stuff as that. I would see clumsy, work-hardened, calloused hands scrawling and scratching signatures on the contract, agreeing to highway robbery interest rates in the fine print that never was read.

* From what I could gather, the recruitment attitude at the temple seemed to me to amount to a self-defeating waiting view...an assumption that Allah would bring us more Muslims. I felt that Allah would be more inclined to help those who helped themselves. I had lived for years in ghetto streets; I knew the Negroes in those streets. Harlem or Detroit were no different. I said I disagreed, that I thought we should go out into the streets and get more Muslims into the fold. All of my life, as you know, I had been an activist, I had been impatient.

* Mr. Muhammad and I are not together today only because of envy and jealousy. I had more faith in Elijah Muhammad than I could ever have in any other man upon this earth.

* My brothers and sisters, our white slavemaster's Christian religion has taught us black people here in the wilderness of North America that we will sprout wings when we die and fly up into the sky where God will have for us a special place called heaven. This is white man's Christian religion used to brainwash us black people! We have accepted it! We have embraced it! We have believed it! We have practiced it! And while we are doing all of that, for himself, this blue-eyed devil has twisted his Christianity, to keep his foot on our backs...to keep our eyes fixed on the pie in the sky and heaven in the hereafter...while he enjoys his heaven right here...on this earth...in this life.

* This white man always has controlled us black people by keeping us running to him begging, 'Please, lawdy, please, Mr. White Man, boss, would you push me off another crumb down from your table that's sagging with riches...'

* You see me—well, in the streets they used to call me Detroit Red. Yes! Yes, that raping, red-headed devil was my grandfather! That close, yes! Mymother's father! She didn't like to speak of it, can you blame her? She said she never laid eyes on him! She was glad for that! I'm glad for her! If I could drain away his blood that pollutes my body, and pollutes my complexion, I'd do it! Because I hate every drop of the rapist's blood that's in me!

* And it's not just me, it's all of us! During slavery, think of it, it was a rare one of our black grandmothers, our great-grandmothers and our great-great-grandmothers who escaped the white rapist slavemaster. That rapist slavemaster who emasculated the black man...with threats, with fear...until even today the black man lives with fear of the white man in his heart! Lives even today still under the heel of the white man!  Think of it—think of that black slave man filled with fear and dread, hearing the screams of his wife, his mother, his daughter being taken—in the barn, the kitchen, in the bushes! Think of it, my dear brothers and sisters! Think of hearing wives, mothers, daughters, being raped! And you were too filled with fear of the rapist to do anything about it! And his vicious, animal attacks' offspring, this white man named things like 'mulatto' and 'quadroon' and 'octoroon' and all those other things that he has called us—you and me—when he is not calling us 'nigger'! Turn around and look at each other, brothers and sisters, and think of this! You and me, polluted all these colors—and this devil has the arrogance and the gall to think we, his victims, should love him!

* I would become so choked up that sometimes I would walk in the streets until late into the night. Sometimes I would speak to no one for hours, thinking to myself about what the white man had done to our poor people here in America.

* They asked if I knew what "conscientious objector" meant. I told them that when the white man asked me to go off somewhere and fight and maybe die to preserve the way the white man treated the black man in America, then my conscience made me object.

* Do you know why the white man really hates you? It's because every time he sees your face, he sees a mirror of his crime—and his guilty conscience can't bear to face it!

* Every white man in America, when he looks into a black man's eyes, should fall to his knees and say 'I'm sorry, I'm sorry—my kind has committed history's greatest crime against your kind; will you give me the chance to atone?' But do you brothers and sisters expect any white man to do that? No, you know better! And why won't he do it? Because he can't do it. The white man has created a devil, to bring chaos upon this earth....

* One day, I remember, a dirty glass of water was on a counter and Mr. Muhammad put a clean glass of water beside it. "You want to know how to spread my teachings?" he said, and he pointed to the glasses of water. "Don't condemn if you see a person has a dirty glass of water," he said, "just show them the clean glass of water that you have. When they inspect it, you won't have to say that yours is better."  Of all the things that Mr. Muhammad ever was to teach me, I don't know why, that still stands out in my mind, although I haven't always practiced it. I love too much to battle. I'm inclined to tell somebody if his glass of water is dirty.

* I was his most faithful servant, and I know today that I did believe in him more firmly than he believed in himself.

* Everything that happens—Islam teaches—is written.

* I know you don't realize the enormity, the horrors, of the so-called Christian white man's crime....  Not even in the Bible is there such a crime! God in His wrath struck down with fire the perpetrators of lesser crimes! One hundred million of us black people! Your grandparents! Mine! Murdered by this white man. To get fifteen million of us here to make us his slaves, on the way he murdered one hundred million! I wish it was possible for me to show you the sea bottom in those days—the black bodies, the blood, the bones broken by boots and clubs! The pregnant black women who were thrown overboard if they got too sick! Thrown overboard to the sharks that had learned that following these slave ships was the way to grow fat!  Why, the white man's raping of the black race's woman began right on those slave ships! The blue-eyed devil could not even wait until he got them here! Why, brothers and sisters, civilized mankind has never known such an orgy of greed and lust and murder....

* The dramatization of slavery never failed intensely to arouse Negroes hearing its horrors spelled out for the first time. It's unbelievable how many black men and women have let the white man fool them into holding an almost romantic idea of what slave days were like.

* Do nothing unto anyone that you would not like to have done unto yourself. Seek peace, and never be the aggressor—but if anyone attacks you, we do not teach you to turn the other cheek. May Allah bless you to be successful and victorious in all that you do.

* (People don't want to believe the sums that even the minor underworld handles. Why, listen: in March 1964, a Chicago nickel-and-dime bets Wheel of Fortune man, Lawrence Wakefield, died, and over $760,000 in cash was in his apartment, in sacks and bags...all taken from poor Negroes...and we wonder why we stay so poor.)

* The wire worked to locate West Indian Archie for me. The wire of the streets, when it wants to, is something like Western Union with the F.B.I. for messengers.

* Have you ever seen someone who seemed a ghost of the person you remembered? It took him a few seconds to fix me in his memory. He claimed, hoarsely, "Red! I'm so glad to see you!"  I all but hugged the old man. He was sick in that weak way. I helped him back. He sat down on the edge of his bed. I sat in his one chair, and I told him how his forcing me out of Harlem had saved my life by turning me in the direction of Islam.  He said, "I always liked you, Red," and he said that he had never really wanted to kill me. I told him it had made me shudder many times to think how close we had come to killing each other. I told him I had sincerely thought I had hit that combinated six-way number for the three hundred dollars he had paid me. Archie said that he had later wondered if he had made some mistake, since I was so ready to die about it. And then we agreed that it wasn't worth even talking about, it didn't mean anything anymore. He kept saying, over and over, in between other things, that he was so glad to see me.

* The blond-haired, blue-eyed white man has taught you and me to worship a white Jesus, and to shout and sing and pray to this God that's his God, the white man's God. The white man has taught us to shout and sing and pray until we die, to wait until death, for some dreamy heaven-in-the-hereafter, when we're dead, while this white man has his milk and honey in the streets paved with golden dollars right here on this earth!

* You don't want to believe what I am telling you, brothers and sisters? Well, I'll tell you what you do. You go out of here, you just take a good look around where you live. Look at not only how you live, but look at how anybody that you know lives—that way, you'll be sure that you're not justa bad-luck accident. And when you get through looking at where you live, then you take you a walk down across Central Park, and start to look at what this white God had brought to the white man. I mean, take yourself a look down there at how the white man is living!

* Go right on down to the tip of Manhattan Island that this devilish white man stole from the trusting Indians for twenty-four dollars! Look at his City Hall, down there; look at his Wall Street! Look at yourself! Look at his God!

* In five months, I put about 30,000 miles of "fishing" on that car before I had an accident. Late one night a brother and I were coming through Weathersfield, Connecticut, when I stopped for a red light and a car smashed into me from behind. I was just shook up, not hurt. That excited devil had a woman with him, hiding her face, so I knew she wasn't his wife. We were exchanging our identification (he lived in Meriden, Connecticut) when the police arrived, and their actions told me he was somebody important. I later found out he was one of Connecticut's most prominent politicians; I won't call his name. Anyway, Temple Seven settled on a lawyer's advice, and that money went down on an Oldsmobile, the make of car I've been driving ever since.

* My feeling about in-laws was that they were outlaws.

* Most numbers I memorized, but I had always made it some point never to memorize her number. Somebody got her to the phone finally. She said, "Oh, hello, Brother Minister—" I just said it to her direct: "Look, do you want to get married?" Naturally, she acted all surprised and shocked.  The more I have thought about it, to this day I believe she was only putting on an act. Because women know. They know.  She said, just like I knew she would, "Yes."

* An old hunchbacked white man performed the wedding. And all of the witnesses were white. Where you are supposed to say all those "I do's," we did. They were all standing there, smiling and watching every move. The old devil said, "I pronounce you man and wife," and then, "Kiss your bride."

* An old hunchbacked white man performed the wedding. And all of the witnesses were white. Where you are supposed to say all those "I do's," we did. They were all standing there, smiling and watching every move. The old devil said, "I pronounce you man and wife," and then, "Kiss your bride."

* You see, Islam is the only religion that gives both husband and wife a true understanding of what love is. The Western "love" concept, you take it apart, it really is lust. But love transcends just the physical. Love is disposition, behavior, attitude, thoughts, likes, dislikes—these things make a beautiful woman, a beautiful wife. This is the beauty that never fades. You find in your Western civilization that when a man's wife's physical beauty fails, she loses her attraction. But Islam teaches us to look into the woman, and teaches her to look into us.

* Two white policemen, breaking up a street scuffle between some Negroes, ordered other Negro passers-by to "Move on!" Of these bystanders, two happened to be Muslim brother Johnson Hinton and another brother of Temple Seven. They didn't scatter and run the way the white cops wanted. Brother Hinton was attacked with nightsticks. His scalp was split open, and a police car came and he was taken to a nearby precinct.  The second brother telephoned our restaurant. And with some telephone calls, in less than half an hour about fifty of Temple Seven's men of the Fruit of Islam were standing in ranks-formation outside the police precinct house.  Other Negroes, curious, came running, and gathered in excitement behind the Muslims. The police, coming to the station house front door, and looking out of the windows, couldn't believe what they saw. I went in, as the minister of Temple Seven, and demanded to see our brother. The police first said he wasn't there. Then they admitted he was, but said I couldn't see him. I said that until he was seen, and we were sure he received proper medical attention, the Muslims would remain where they were.  They were nervous and scared of the gathering crowd outside. When I saw our Brother Hinton, it was all I could do to contain myself. He was only semiconscious. Blood had bathed his head and face and shoulder. I hope I never again have to withstand seeing another case of sheer police brutality like that.  I told the lieutenant in charge, "That man belongs in the hospital." They called an ambulance.

* A high police official came up to me, saying "Get those people out of there." I told him that our brothers were standing peacefully, disciplined perfectly, and harming no one. He told me those others, behind them, weren't disciplined. I politely told him those others were his problem.

* I named the newspaper Muhammad Speaks and Muslim brothers sold it on the ghetto sidewalks. Little did I dream that later on, when jealousy set in among the hierarchy, nothing about me would be printed in the paper I had founded.

* Here was one of the white man's most characteristic behavior patterns—where black men are concerned. He loves himself so much that he is startled if he discovers that his victims don't share his vainglorious self-opinion. In America for centuries it had been just fine as long as the victimized, brutalized and exploited black people had been grinning and begging and "Yessa, Massa" and Uncle Tomming. But now, things were different. First came the white newspapers feature writers and columnists: "Alarming"..."hate-messengers"..."threat to the good relations between the races"..."black segregationists"..."black supremacists," and the like.

* Since slavery, the American white man has always kept some handpicked Negroes who fared much better than the black masses suffering and slaving out in the hot fields. The white man had these "house" and "yard" Negroes for his special servants. He threw them more crumbs from his rich table, he even let them eat in his kitchen. He knew that he could always count on them to keep "good massa" happy in his self-image of being so "good" and "righteous." "Good massa" always heard just what he wanted to hear from these "house" and "yard" blacks. "You're such a good, fine massa!" Or, "Oh, massa, those old black nigger fieldhands out there, they're happy just like they are; why, massa, they're not intelligent enough for you to try and do any better for them, massa—"  Well, slavery time's "house" and "yard" Negroes had become more sophisticated, that was all. When now the white man picked up his telephone and dialed his "house" and "yard" Negroes why, he didn't even need to instruct the trained black puppets. They had seen the television program; had read the newspapers. They were already composing their lines. They knew what to do.

* One funny thing—in all that hectic period, something quickly struck my notice: the Europeans never pressed the "hate" question. Only the American white man was so plagued and obsessed with being "hated." He was so guilty, it was clear to me, of hating Negroes.

* The white man doesn't want the blacks! He doesn't want the blacks that are a parasite upon him! He doesn't want this black man whose presence and condition in this country expose the white man to the world for what he is!

* For the white man to ask the black man if he hates him is just like the rapist asking the raped, orthe wolf asking the sheep, 'Do you hate me?' The white man is in no moral position to accuse anyone else of hate! Why, when all of my ancestors are snake-bitten, and I'm snake-bitten, and I warn my children to avoid snakes, what does that snake sound like accusing me of hate-teaching?

* "Mr. Malcolm X," those devils would ask, "why is your Fruit of Islam being trained in judo and karate?" An image of black men learning anything suggesting self-defense seemed to terrify the white man. I'd turn their question around: "Why does judo or karate suddenly get so ominous because black men study it? Across America, the Boy Scouts, the YMCA, even the YWCA, the CYP, PAL—they all teach judo! It's all right, it's fine—until black men teach it! Even little grammar school classes, little girls, are taught to defend themselves—"

* "Christianity is the white man's religion. The Holy Bible in the white man's hands and his interpretations of it have been the greatest single ideological weapon for enslaving millions of non-white human beings. Every country the white man has conquered with his guns, he has always paved the way, and salved his conscience, by carrying the Bible and interpreting it to call the people 'heathens' and 'pagans'; then he sends his guns, then his missionaries behind the guns to mop up—

* Well, let's go back to the Greek, and maybe you will learn the first thing you need to know about the word 'demagogue.' 'Demagogue' means, actually, 'teacher of the people.' And let's examine some demagogues. The greatest of all Greeks, Socrates, was killed as a 'demagogue.' Jesus Christ died on the cross because the Pharisees of His day were upholding their law, not the spirit. The modern Pharisees are trying to heap destruction upon Mr. Muhammad, calling him a demagogue, a crackpot, and fanatic. What about Gandhi? The man that Churchill called 'a naked little fakir,' refusing food in a British jail? But then a quarter of a billion people, a whole subcontinent, rallied behind Gandhi—and they twisted the British lion's tail! What about Galileo, standing before his inquisitors, saying 'The earth does move!' What about Martin Luther, nailing on a door his thesis against the all-powerful Catholic church which called him 'heretic'? We, the followers of The Honorable Elijah Muhammad, are today in the ghettoes as once the sect of Christianity's followers were like termites in the catacombs and the grottoes—and they were preparing the grave of the mighty Roman Empire!"

* The reporters would try their utmost to raise some "good" white man whom I couldn't refute as such. I'll never forget how one practically lost his voice. He asked me did I feel any white men had ever done anything for the black man in America. I told him, "Yes, I can think of two. Hitler, and Stalin. The black man in America couldn't get a decent factory job until Hitler put so much pressure on the white man. And then Stalin kept up the pressure—"

* Today's Uncle Tom doesn't wear a handkerchief on his head. This modern, twentieth-century Uncle Thomas now often wears a top hat. He's usually well-dressed and well-educated. He's often the personification of culture and refinement. The twentieth-century Uncle Thomas sometimes speaks with a Yale or Harvard accent. Sometimes he is known as Professor, Doctor, Judge, and Reverend, even Right Reverend Doctor. This twentieth-century Uncle Thomas is a professional Negro...by that I mean his profession is being a Negro for the white man.

* "Black bodies with white heads!" I called them what they were. Every one of those "Negroprogress" organizations had the same composition. Black "leaders" were out in the public eye to be seen by the Negroes for whom they were supposed to be fighting the white man. But obscurely, behind the scenes, was a white boss—a president, or board chairman, or some other title, pulling the real strings.

* I'd walk into those studios. The devils and black Ph.D. puppets would be acting so friendly and "integrated" with each other—laughing and calling each other by first names, and all that; it was such a big lie it made me sick in my stomach. They would even be trying to act friendly toward me—we all knowing they had asked me there to try and beat out my brains. They would offer me coffee. I would tell them "No, thanks," to please just tell me where was I supposed to sit.

* The Western world's most learned diplomats have failed to solve this grave race problem. Her learned legal experts have failed. Her sociologists have failed. Her civil leaders have failed. Her fraternal leaders have failed. Since all of these have failed to solve this race problem, it is time for us to sit down and reason! I am certain that we will be forced to agree that it takes God Himself to solve this grave racial dilemma."

* Anyone who has listened to me will have to agree that I believed in Elijah Muhammad and represented him one hundred percent. I never tried to take any credit for myself.

* The greatest miracle Christianity has achieved in America is that the black man in white Christian hands has not grown violent. It is a miracle that 22 million black people have not risen up against their oppressors—in which they would have been justified by all moral criteria, and even by the democratic tradition! It is a miracle that a nation of black people has so fervently continued to believe in a turn-the-other-cheek and heaven-for-you-after-you-die philosophy! It is a miracle that the American black people have remained a peaceful people, while catching all the centuries of hell that they have caught, here in white man's heaven! The miracle is that the white man's puppet Negro 'leaders,' his preachers and the educated Negroes laden with degrees, and others who have been allowed to wax fat off their black poor brothers, have been able to hold the black masses quiet until now.

* From the airport to the rally hall, Mr. Muhammad's motorcade had a siren-screaming police escort. Law agencies once had scoffed at our Nation as "black crackpots"; now they took special pains to safeguard against some "white crackpots" causing any "incidents" or "accidents."

* The white man was barred from attendance—the first time the American black man had ever dreamed of such a thing. And that brought us new attacks from the white man and his black puppets. "Black segregationists...racists!" Accusing us of segregation! Across America, whites barring blacks was standard.

* Any alcohol and tobacco had to be checked, and any objects which could possibly be used to attempt to harm Mr. Muhammad. He always seemed deathly afraid that someone would harm him, and he insisted that everyone be searched to forestall this. Today I understand better, why.

* I would watch also the faces of the professional black men, the so-called intellectuals who attacked us. They possessed the academic know-how, they possessed the technical and the scientific skills that could help to lead their mass of poor, black brothers out of our condition. But all these intellectual and professional black men could seem to think of was humbling themselves, and begging, trying to "integrate" with the so-called "liberal" white man who was telling them, "In time...everything's going to work out one day...just wait and have patience." These intellectual and professional Negroes couldn't use what they knew for the benefit of their own black kind simply because even among themselves they were disunited. United among themselves, united with their own kind, they could have benefited black people all over the world!  I would watch the faces of those intellectual and professional Negroes growing grave, and set as the truth hit home to them.

* I would watch also the faces of the professional black men, the so-called intellectuals who attacked us. They possessed the academic know-how, they possessed the technical and the scientific skills that could help to lead their mass of poor, black brothers out of our condition. But all these intellectual and professional black men could seem to think of was humbling themselves, and begging, trying to "integrate" with the so-called "liberal" white man who was telling them, "In time...everything's going to work out one day...just wait and have patience." These intellectual and professional Negroes couldn't use what they knew for the benefit of their own black kind simply because even among themselves they were disunited. United among themselves, united with their own kind, they could have benefited black people all over the world!  I would watch the faces of those intellectual and professional Negroes growing grave, and set as the truth hit home to them.

* No Muslim smokes—that was another of our rules. Some prospective Muslims found it more difficult to quit tobacco than others found quitting the dope habit. But black men and women quit more easily when we got them to consider seriously how the white man's government cared less about the public's health than about continuing the tobacco industry's billions in tax revenue. "What does a serviceman pay for a carton of cigarettes?" a prospective Muslim convert would be asked. It helped him to see that every regularly priced carton he bought meant that the white man's government took around two dollars of a black man's hard-earned money for taxes, not for tobacco.

* You may have read somewhere—a lot has been written concerning it—about the Nation of Islam's phenomenal record of dope-addiction cures of longtime junkies. In fact, the New York Times carried a story about how some of the social agencies have asked representatives of the Muslim program for clinical suggestions.  The Muslim program began with recognizing that color and addiction have a distinct connection. It is no accident that in the entire Western Hemisphere, the greatest localized concentration of addicts is in Harlem.  Our cure program's first major ingredient was the painfully patient work of Muslims who previously were junkies themselves.  In the ghetto's dope jungle, the Muslim ex-junkies would fish out addicts who knew them back in those days. Then with an agonizing patience that might span anywhere from a few months to a year, our ex-junky Muslims would conduct the addicts through the Muslim six-point therapeutic process.  The addict first was brought to admit to himself that he was an addict. Secondly, he was taught why he used narcotics. Third, he was shown that there was a way to stop addiction. Fourth, the addict's shattered self-image, and ego, were built up until the addict realized that he had, within,the self-power to end his addiction. Fifth, the addict voluntarily underwent a cold turkey break with drugs. Sixth, finally cured, now an ex-addict completes the cycle by "fishing" up other addicts whom he knows, and supervising their salvaging.

* If some white man, or "approved" black man, created a narcotics cure program as successful as the one conducted under the aegis of the Muslims, why, there would be government subsidy, and praise and spotlights, and headlines. But we were attacked instead. Why shouldn't the Muslims be subsidized to save millions of dollars a year for the government and the cities? I don't know what addicts' crimes cost nationally, but it is said to be billions a year in New York City. An estimated $12 million a year is lost to thieves in Harlem alone.  An addict doesn't work to supply his habit, which may cost anywhere from ten to fifty dollars a day. How could he earn that much? No! The addict steals, he hustles in other ways; he preys upon other human beings like a hawk or a vulture—as I did. Very likely, he is a school drop-out, the same as I was, an Army reject, psychologically unsuited to a job even if he was offered one, the same as I was.

* "But, Brother Malcolm, there is something you need to know. You will grow to be hated when you become well known. Because usually people get jealous of public figures."Nothing that Mr. Muhammad ever said to me was more prophetic.

* The more places I represented Mr. Muhammad on television and radio, and at colleges and elsewhere, the more letters came from people who had heard me. I'd say that ninety-five per cent of the letters were from white people.  Only a few of the letters fell into the "Dear Nigger X" category, or the death-threats. Most of my mail exposed to me the white man's two major dreads. The first one was his own private belief that God wrathfully is going to destroy this civilization. And the white man's second most pervading dread was his image of the black man entering the body of the white woman.

* Unless we call one white man, by name, a 'devil,' we are not speaking of any individual white man. We are speaking of the collective white man's historical record. We are speaking of the collective white man's cruelties, and evils, and greeds, that have seen him act like a devil toward the non-white man. Any intelligent, honest, objective person cannot fail to realize that this white man's slave trade, and his subsequent devilish actions are directly responsible for not only the presence of this black man in America, but also for the condition in which we find this black man here. You cannot find one black man, I do not care who he is, who has not been personally damaged in some way by the devilish acts of the collective white man!

* Those social workers and sociologists—they tried to take me apart. Especially the black ones, for some reason. Of course, I knew the reason: the white man signed their paychecks. If I wasn't "polarizing the community," according to this bunch, I had "erroneously appraised the racial picture." Or in some statement, I had "over-generalized." Or when I had made some absolutely true point, "Malcolm X conveniently manipulated..."

* The white man—give him his due—has an extraordinary intelligence, an extraordinary cleverness. His world is full of proof of it. You can't name a thing the white man can't make. You can hardly name a scientific problem he can't solve. Here he is now solving the problems of sending men exploring into outer space—and returning them safely to earth.  But in the arena of dealing with human beings, the white man's working intelligence is hobbled. His intelligence will fail him altogether if the humans happen to be non-white. The white man's emotions superseded his intelligence. He will commit against non-whites the most incredible spontaneous emotional acts, so psyche-deep is his "white superiority" complex.

* Where was the A-bomb dropped..."to save American lives"? Can the white man be so naive as to think the clear import of this ever will be lost upon the non-white two-thirds of the earth's population?

* What else but a controlling emotional "devil" so blinded American white intelligence that it couldn't foresee that millions of black slaves, "freed," then permitted even limited education, would one day rise up as a terrifying monster within white America's midst?  The white man's brains that today explore space should have told the slavemaster that any slave, if he is educated, will no longer fear his master. History shows that an educated slave always begins to ask, and next demand, equality with his master.Today, in many ways the black man sees the collective white man in America better than that white man can see himself. And the 22 million blacks realize increasingly that physically, politically, economically, and even to some degree socially, the aroused black man can create a turmoil in white America's vitals—not to mention America's international image.

* No one will ever know exactly what emotional ingredient made this relatively trivial incident a fuse for those Montgomery Negroes. There had been centuries of the worst kind of outrages against Southern black people—lynchings, rapings, shootings, beatings! But you know history has been triggered by trivial-seeming incidents. Once a little nobody Indian lawyer was put off a train, and fed up with injustice, he twisted a knot in the British Lion's tail. His name was Mahatma Gandhi!

* Well, sir, I see the same boycott reasoning for Negroes asked to join the Army, Navy, and Air Force. Why should we go off to die somewhere to preserve a so-called 'democracy' that gives awhite immigrant of one day more than it gives the black man with four hundred years of slaving and serving in this country?"

* The Deep South white press generally blacked me out. But they front-paged what I felt about Northern white and black Freedom Riders going South to "demonstrate." I called it "ridiculous"; their own Northern ghettoes, right at home, had enough rats and roaches to kill to keep all of the Freedom Riders busy. I said that ultra-liberal New York had more integration problems than Mississippi. If the Northern Freedom Riders wanted more to do, they could work on the roots of such ghetto evils as the little children out in the streets at midnight, with apartment keys on strings around their necks to let themselves in, and their mothers and fathers drunk, drug addicts, thieves, prostitutes. Or the Northern Freedom Riders could light some fires under Northern city halls, unions, and major industries to give more jobs to Negroes to remove so many of them from the relief and welfare rolls, which created laziness, and which deteriorated the ghettoes into steadily worse places for humans to live. It was all—it is all—the absolute truth; but what did I want to say it for? Snakes couldn't have turned on me faster than the liberal.

* Yes, I will pull off that liberal's halo that he spends such efforts cultivating! The North's liberalshave been for so long pointing accusing fingers at the South and getting away with it that they have fits when they are exposed as the world's worst hypocrites.  I believe my own life mirrors this hypocrisy. I know nothing about the South. I am a creation of the Northern white man and of his hypocritical attitude toward the Negro.

* The white Southerner was always given his due by Mr. Muhammad. The white Southerner, you can say one thing—he is honest. He bares his teeth to the black man; he tells the black man, to his face, that Southern whites never will accept phony "integration." The Southern white goes further, to tell the black man that he means to fight him every inch of the way—against even the so-called "tokenism." The advantage of this is the Southern black man never has been under any illusions about the opposition he is dealing with.

* Actually, America's most dangerous and threatening black man is the one who has been kept sealed up by the Northerner in the black ghettoes—the Northern white power structure's system to keep talking democracy while keeping the black man out of sight somewhere, around the corner.

* I'm telling it like it is! You never have to worry about me biting my tongue if something I know as truth is on my mind. Raw, naked truth exchanged between the black man and the white man is what a whole lot more of is needed in this country—to clear the air of the racial mirages, clichés, and lies that this country's very atmosphere has been filled with for four hundred years.

* The white men belonging to the power structures in thousands of communities across America know that I'm right! They know that I am describing what has been the true pattern of "communications" between the "local whites of good-will" and the local Negroes. It has been a pattern created by domineering, ego-ridden whites. Its characteristic design permitted the white man to feel "noble" about throwing crumbs to the black man, instead of feeling guilty about thelocal community's system of cruelly exploiting Negroes.

* But I want to tell you something. This pattern, this "system" that the white man created, of teaching Negroes to hide the truth from him behind a façade of grinning, "yessir-bossing," foot shuffling and head-scratching—that system has done the American white man more harm than an invading army would do to him.  Why do I say this? Because all this has steadily helped this American white man to build up, deep in his psyche, absolute conviction that he is "superior." In how many, many communities have, thus, white men who didn't finish high school regarded condescendingly university-educated local Negro "leaders," principals of schools, teachers, doctors, other professionals?

* Let's just face truth. Facts! Whether or not the white man of the world is able to face truth, and facts, about the true reasons for his troubles—that's what essentially will determine whether or not he will now survive.

* Today we are seeing this revolution of the non-white peoples, who just a few years ago would have frozen in horror if the mighty white nations so much as lifted an eyebrow. What it is, simply, is that black and brown and red and yellow peoples have, after hundreds of years of exploitation and imposed "inferiority" and general misuse, become, finally, do-or-die sick and tired of the white man's heel on their necks.

* How can the white American government figure on selling "democracy" and "brotherhood" to non-white peoples—if they read and hear every day what's going on right here in America, and see the better-than-a-thousand-words photographs of the American white man denying "democracy" and "brotherhood" even to America's native-born non-whites? The world's non whites know how this Negro here has loved the American white man, and slaved for him, tended to him, nursed him. This Negro has jumped into uniform and gone off and died when this America was attacked by enemies both white and non-white. Such a faithful, loyal non-white as this—and still America bombs him, and sets dogs on him, and turns fire hoses on him, and jails him by the thousands, and beats him bloody, and inflicts upon him all manner of other crimes.  Is it clear why I have said that the American white man's malignant superiority complex has done him more harm than an invading army?

* One thing the white man never can give the black man is self-respect! The black man never can become independent and recognized as a human being who is truly equal with other human beings until he has what they have, and until he is doing for himself what others are doing for themselves.

* One thing the white man never can give the black man is self-respect! The black man never can become independent and recognized as a human being who is truly equal with other human beings until he has what they have, and until he is doing for himself what others are doing for themselves.

* For an example of what I am talking about—in every black ghetto, Jews own the major businesses. Every night the owners of those businesses go home with that black community's money, which helps the ghetto to stay poor. But I doubt that I have ever uttered this absolute truth before an audience without being hotly challenged, and accused by a Jew of anti-Semitism. Why? I will bet that I have told five hundred such challengers that Jews as a group would never watch some other minority systematically siphoning out their community's resources without doing something about it. I have told them that if I tell the simple truth, it doesn't mean that I am anti-Semitic; it means merely that I am antiexploitation.

* One particular university's "token-integrated" black Ph.D. associate professor I never will forget; he got me so mad I couldn't see straight. As badly as our 22 millions of educationally deprived black people need the help of any brains he has, there he was looking like some fly in the buttermilk among white "colleagues"—and he was trying to eat me up! He was ranting about what a "divisive demagogue" and what a "reverse racist" I was. I was racking my head, to spear that fool; finally I held up my hand, and he stopped. "Do you know what white racists call black Ph.D's?" He said something like, "I believe that I happen not to be aware of that"—you know, one of these ultra-proper-talking Negroes. And I laid the word down on him, loud: "Nigger!"

* Speaking in these colleges and universities was good for the Nation of Islam, I would report to Mr. Muhammad, because the devilish white man's best minds were developed and influenced in the colleges and universities. But for some reason that I could never understand until much later, Mr. Muhammad never really wanted me to speak at these colleges and universities.I was to learn later, from Mr. Muhammad's own sons at he was envious because he felt unequipped to speak at colleges himself.

* Time and time again, the black, the brown, the red, and the yellow races have witnessed and suffered the white man's small ability to understand the simple notes of the spirit. The white man seems tone deaf to the total orchestration of humanity. Every day, his newspapers' front pages show us the world that he has created. God's wrathful judgment is close upon this white man stumbling and groping blindly in wickedness and evil and spiritual darkness.

* God's wrathful judgment is close upon this white man stumbling and groping blindly in wickedness and evil and spiritual darkness.

* The collective white man's history has left the non-white peoples no alternative, either, but to draw closer to each other.

* Characteristically, as always, the devilish white man lacks the moral strength and courage to cast off his arrogance. He wants, today, to 'buy' friends among the non-whites. He tries, characteristically, to cover up his past record. He does not possess the humility to admit his guilt, to try and atone for his crimes. The white man has perverted the simple message of love that the Prophet Jesus lived and taught when He walked upon this earth.

* Anyway, I'd never seen anyone I ever spoke before more affected than this little white college girl. She demanded right up in my face, "Don't you believe there are any good white people?" I didn't want to hurt her feelings. I told her, "People's deeds I believe in, Miss—not their words."  "What can I do?" she exclaimed. I told her, "Nothing." She burst out crying, and ran out and up Lenox Avenue and caught a taxi.

* I was the invited speaker at the Harvard Law School Forum. I happened to glance through a window. Abruptly, I realized that I was looking in the direction of the apartment house that was my old burglary gang's hideout.  It rocked me like a tidal wave. Scenes from my once depraved life lashed through my mind. Living like an animal; thinking like an animal!  Awareness came surging up in me—how deeply the religion of Islam had reached down into the mud to lift me up, to save me from being what I inevitably would have been: a dead criminal in a grave, or, if still alive, a flint-hard, bitter, thirty-seven-year-old convict in some penitentiary, or insane asylum. Or, at best, I would have been an old, fading Detroit Red, hustling, stealing enough for food and narcotics, and myself being stalked as prey by cruelly ambitious youngerhustlers such as Detroit Red had been.  But Allah had blessed me to learn about the religion of Islam, which had enabled me to lift myself up from the muck and the mire of this rotting world.  And there I stood, the invited speaker, at Harvard.

* A story that I had read in prison when I was reading a lot of Greek mythology flicked into my head.  The boy Icarus. Do you remember the story?  Icarus' father made some wings that he fastened with wax. "Never fly but so high with these wings," the father said. But soaring around, this way, that way, Icarus' flying pleased him so that he began thinking he was flying on his own merit. Higher, he flew—higher—until the heat of the sun melted the wax holding those wings. And down came Icarus—tumbling.  Standing there by that Harvard window, I silently vowed to Allah that I never would forget that any wings I wore had been put on by the religion of Islam. That fact I never have forgotten...not for one second.

* As far back as 1955, I had heard hints. But believe me when I tell you this: for me even to consider believing anything as insane-sounding as any slightest implication of any immoral behavior of Mr. Muhammad—why, the very idea made me shake with fear.  And so my mind simply refused to accept anything so grotesque as adultery mentioned in the same breath with Mr. Muhammad's name.

* I don't think I could say anything which better testifies to my depth of faith in Mr. Muhammad than that I totally and absolutely rejected my own intelligence. I simply refused to believe. I didn't want Allah to "burn my brain" as I felt the brain of my brother Reginald had been burned for harboring evil thoughts about Mr. Elijah Muhammad. The last time I had seen Reginald, one day he walked into the Mosque Seven restaurant. I saw him coming in the door. I went and met him. I looked into my own brother's eyes; I told him he wasn't welcome among Muslims, and he turned around and left, and I haven't seen him since. I did that to my own blood brother because, years before, Mr. Muhammad had sentenced Reginald to "isolation" from all other Muslims—and I considered that I was a Muslim before I was Reginald's brother.

* There was never any specific moment when I admitted the situation to myself. In the way thatthe human mind can do, somehow I slid over admitting to myself the ugly fact, even as I began dealing with it.

* Next, I broke the rule that no Muslim is supposed to have any contact with another Muslim in the "isolated" state. I looked up, and I talked with three of the former secretaries to Mr. Muhammad. From their own mouths, I heard their stories of who had fathered their children. And from their own mouths I heard that Elijah Muhammad had told them I was the best, the greatest minister he ever had, but that someday I would leave him, turn against him—so I was "dangerous." I learned from these former secretaries of Mr. Muhammad that while he was praising me to my face, he was tearing me apart behind my back.  That deeply hurt me.

* The thing to me worse than death was the betrayal. I could conceive death. I couldn't conceive betrayal—not of the loyalty which I had given to the Nation of Islam, and to Mr. Muhammad. During the previous twelve years, if Mr. Muhammad had committed any civil crime punishable by death, I would have said and tried to prove that I did it to save him—and I would have gone to the electric chair, as Mr. Muhammad's servant.

* What began to break my faith was that, try as I might, I couldn't hide, I couldn't evade, that Mr. Muhammad, instead of facing what he had done before his followers, as a human weakness or as fulfillment of prophecy—which I sincerely believe that Muslims would have understood, or at least they would have accepted—Mr. Muhammad had, instead, been willing to hide, to cover up what he had done.

* What Sonny Liston was about to meet, in fact, was one of the most awesome frights that ever can confront any person—one who worships Allah, and who is completely without fear.

* The first direct order for my death was issued through a Mosque Seven official who previously had been a close assistant. Another previously close assistant of mine was assigned to do the job. He was a brother with a knowledge of demolition; he was asked to wire my car to explode when I turned the ignition key. But this brother, it happened, had seen too much of my total loyalty to the Nation to carry out his order. Instead, he came to me. I thanked him for my life. I told him what was really going on in Chicago. He was stunned almost beyond belief.  This brother was close to others in the Mosque Seven circle who might subsequently be called upon to eliminate me. He said he would take it upon himself to enlighten each of them enough so that they wouldn't allow themselves to be used.  This first direct death-order was how, finally, I began to arrive at my psychological divorce from the Nation of Islam.

* I knew that in any society, a true leader is one who earns and deserves the following he enjoys. True followers are bestowed by themselves, out of their own volition and emotions.

* And because I had been a hustler, I knew better than all whites knew, and better than nearly all of the black "leaders" knew, that actually the most dangerous black man in America was the ghetto hustler.  Why do I say this? The hustler, out there in the ghetto jungles, has less respect for the white power structure than any other Negro in North America. The ghetto hustler is internally restrained by nothing. He has no religion, no concept of morality, no civic responsibility, no fea —nothing. To survive, he is out there constantly preying upon others, probing for any human weakness like a ferret. The ghetto hustler is forever frustrated, restless, and anxious for some "action." Whatever he undertakes, he commits himself to it fully, absolutely.  What makes the ghetto hustler yet more dangerous is his "glamor" image to the school-dropout youth in the ghetto. These ghetto teen-agers see the hell caught by their parents struggling to get somewhere, or see that they have given up struggling in the prejudiced, intolerant white man's world. The ghetto teen-agers make up their own minds they would rather be like the hustlers whom they see dressed "sharp" and flashing money and displaying no respect for anybody or anything. So the ghetto youth become attracted to the hustler worlds of dope, thievery, prostitution, and general crime and immorality.

* It scared me the first time I really saw the danger of these ghetto teen-agers if they are ever sparked to violence. One sweltering summer afternoon, I attended a Harlem street rally which contained a lot of these teen-agers in the crowd. I had been invited by some "responsible" Negro leaders who normally never spoke to me; I knew they had just used my name to help them draw a crowd. The more I thought about it on the way there, the hotter I got. And when I got on the stand, I just told that crowd in the street that I wasn't really wanted up there, that my name had been used—and I walked off the speaker's stand.  Well, what did I want to do that for? Why, those young, teenage Negroes got upset, and started milling around and yelling, upsetting the older Negroes in the crowd. The first thing you know traffic was blocked in four directions by a crowd whose mood quickly grew so ugly that I really got apprehensive. I got up on top of a car and began waving my arms and yelling at them to quiet down. They did quiet, and then I asked them to disperse—and they did.  This was when it began being said that I was America's only Negro who "could stop a race riot or start one." I don't know if I could do either one. But I know one thing: it had taught me in a very few minutes to have a whole lot of respect for the human combustion that is packed among the hustlers and their young admirers who live in the ghettoes where the Northern white man has sealed-off the Negro—away from whites—for a hundred years.

* I felt a challenge to plan, and build, an organization that could help to cure the black man in North America of the sickness which has kept him under the white man's heel.  The black man in North America was mentally sick in his cooperative, sheeplike acceptance of the white man's culture.  The black man in North America was spiritually sick because for centuries he had accepted the white man's Christianity—which asked the black so-called Christian to expect no true Brotherhood of Man, but to endure the cruelties of the white so-called Christians. Christianity had made black men fuzzy, nebulous, confused in their thinking. It had taught the black man to think if he had no shoes, and was hungry, "we gonna get shoes and milk and honey and fish fries in Heaven."  The black man in North America was economically sick and that was evident in one simple fact: as a consumer, he got less than his share, and as a producer gave least. The black American today shows us the perfect parasite image—the black tick under the delusion that he is progressing because he rides on the udder of the fat, three-stomached cow that is white America. For instance, annually, the black man spends over $3 billion for automobiles, but America contains hardly any franchised black automobile dealers. For instance, forty per cent of the expensive imported Scotch whisky consumed in America goes down the throats of the status-sick black man; but the only black-owned distilleries are in bathtubs, or in the woods somewhere. Or for instance—a scandalous shame—in New York City, with over a million Negroes, there aren't twenty black-owned businesses employing over ten people. It's because black men don't own and control their own community's retail establishments that they can't stabilize their own community.The black man in North America was sickest of all politically. He let the white man divide him into such foolishness as considering himself a black "Democrat," a black "Republican," a black "Conservative," or a black "Liberal"...when a ten-million black vote bloc could be the deciding balance of power in American politics, because the white man's vote is almost always evenly divided. The polls are one place where every black man could fight the black man's cause with dignity, and with the power and the tools that the white man understands, and respects, and fears, and cooperates with. Listen, let me tell you something! If a black bloc committee told Washington's worst "nigger-hater," "We represent ten million votes," why, that "nigger-hater" would leap up: "Well, how are you? Come on in here!" Why, if the Mississippi black man voted in a bloc, Eastland would pretend to be more liberal than Jacob Javits—or Eastland would not survive in his office. Why else is it that racist politicians fight to keep black men from the polls?

* U.S. politics is ruled by special-interest blocs and lobbies. What group has a more urgent special interest, what group needs a bloc, a lobby, more than the black man?

* Doctors have the best lobby in Washington. Their special-interest influence successfully fights the Medicare program that's wanted, and needed, by millions of other people.

* Twenty-two million black men! They have given America four hundred years of toil; they have bled and died in every battle since the Revolution; they were in America before the Pilgrims, and long before the mass immigrations—and they are still today at the bottom of everything!  Why, twenty-two million black people should tomorrow give a dollar apiece to build a skyscraper lobby building in Washington, D.C. Every morning, every legislator should receive a communication about what the black man in America expects and wants and needs. The demanding voice of the black lobby should be in the ears of every legislator who votes on anyissue.  The cornerstones of this country's operation are economic and political strength and power. The black man doesn't have the economic strength—and it will take time for him to build it. But right now the American black man has the political strength and power to change his destiny overnight.

* Astonishing numbers of white people called, and wrote, offering contributions, or asking could they join? The answer was, no, they couldn't join; our membership was all black—but if their consciences dictated, they could financially help our constructive approach to America's race problems.

* Then one day Dr. Shawarbi and I were introduced by a newspaperman.  He was cordial. He said he had followed me in the press; I said I had been told of him, and we talked for fifteen or twenty minutes. We both had to leave to make appointments we had, when he dropped on me something whose logic never would get out of my head. He said, "No man has believed perfectly until he wishes for his brother what he wishes for himself."

* Allah always gives you signs, when you are with Him, that He is with you.

* I considered it another of Allah's signs, that wherever I turned, someone was there to help me, to guide me.

* The co-pilot was darker than he was. I can't tell you the feeling it gave me. I had never seen a black man flying a jet. That instrument panel: no one ever could know what all of those dials meant! Both of the pilots were smiling at me, treating me with the same honor and respect I had received ever since I left America. I stood there looking through the glass at the sky ahead of us. In America, I had ridden in more planes than probably any other Negro, and I never had been invited up into the cockpit. And there I was, with two Muslim seatmates, one from Egypt, the other from Arabia, all of us bound for Mecca, with me up in the pilots' cabin. Brother, I knew Allah was with me.

* All ate as One, and slept as One. Everything about the pilgrimage atmosphere accented the Oneness of Man under One God.

* Most people think Ethiopia is Christian. But only its government is Christian. The West has always helped to keep the Christian government in power.

* I had just said my Sunset Prayer, El Maghrib; I was lying on my cot in the fourth-tiercompartment, feeling blue and alone, when out of the darkness came a sudden light!

* I was speechless at the man's attitude, and at my own physical feeling of no difference between us as human beings.

* It was early in the morning when we reached Dr. Azzam's home. His father was there, his father's brother, a chemist, and another friend—all up that early, waiting. Each of them embraced me as though I were a long-lost child. I had never seen these men before in my life, and they treated me so good! I am going to tell you that I had never been so honored in my life, nor had I ever received such true hospitality.

* Nothing in either of my two careers as a black man in America had served to give me any idealistic tendencies. My instincts automatically examined the reasons, the motives, of anyone who did anything they didn't have to do for me. Always in my life, if it was any white person, I could see a selfish motive.  But there in that hotel that morning, a telephone call and a few hours away from the cot on the fourth-floor tier of the dormitory, was one of the few times I had been so awed that I was totally without resistance. That white man—at least he would have been considered "white" in Americ —related to Arabia's ruler, to whom he was a close advisor, truly an international man, with nothing in the world to gain, had given up his suite to me, for my transient comfort. He had nothing to gain. He didn't need me. He had everything. In fact, he had more to lose than gain. He had followed the American press about me. If he did that, he knew there was only stigma attached to me. I was supposed to have horns. I was a "racist." I was "anti-white"—and he from all appearances was white. I was supposed to be a criminal; not only that, but everyone was even accusing me of using his religion of Islam as a cloak for my criminal practices and philosophies. Even if he had had some motive to use me, he knew that I was separated from Elijah Muhammad and the Nation of Islam, my "power base," according to the press in America. The only organization that I had was just a few weeks old. I had no job. I had no money. Just to get over there, I had had to borrow money from my sister.

* That morning was when I first began to reappraise the "white man." It was when I first began toperceive that "white man," as commonly used, means complexion only secondarily; primarily it described attitudes and actions. In America, "white man" meant specific attitudes and actions toward the black man, and toward all other non-white men. But in the Muslim world, I had seen that men with white complexions were more genuinely brotherly than anyone else had ever been.  That morning was the start of a radical alteration in my whole outlook about "white" men.

* He spoke of the racial lineage of the descendants of Muhammad the Prophet, and he showed how they were both black and white. He also pointed out how color, the complexities of color, andthe problems of color which exist in the Muslim world, exist only where, and to the extent that, that area of the Muslim world has been influenced by the West. He said that if one encountered any differences based on attitude toward color, this directly reflected the degree of Western influence

* They asked me what about the Hajj had impressed me the most. One of the several who spoke English asked; they translated my answers for the others. My answer to that question was not the one they expected, but it drove home my point.  I said, "The brotherhood! The people of all races, colors, from all over the world coming together as one! It has proved to me the power of the One God."

* It may have been out of taste, but that gave me an opportunity, and I used it, to preach them a quick little sermon on America's racism, and its evils.  I could tell the impact of this upon them. They had been aware that the plight of the black man in America was "bad," but they had not been aware that it was inhuman, that it was a psychological castration. These people from elsewhere around the world were shocked. As Muslims, they had a very tender heart for all unfortunates, and very sensitive feelings for truth and justice. And in everything I said to them, as long as we talked, they were aware of the yardstick that I was using to measure everything—that to me the earth's most explosive and pernicious evil is racism, the inability of God's creatures to live as One, especially in the Western world.

* America needs to understand Islam, because this is the one religion that erases from its society the race problem. Throughout my travels in the Muslim world, I have met, talked to, and even eaten with people who in America would have been considered 'white'—but the 'white' attitude was removed from their minds by the religion of Islam. I have never before seen sincere and true brotherhood practiced by all colors together, irrespective of their color. You may be shocked by these words coming from me. But on this pilgrimage, what I have seen, and experienced, has forced me to re-arrange much of my thought-patterns previously held, and to toss aside some of my previous conclusions. This was not too difficult for me. Despite my firm convictions, I have been always a man who tries to face facts, and to accept the reality of life as new experience and new knowledge unfolds it. I have always kept an open mind, which is necessary to the flexibility that must go hand in hand with every form of intelligent search for truth.

* I could see from this, that perhaps if white Americans could accept the Oneness of God, then perhaps, too, they could accept in reality the Oneness of Man—and cease to measure, and hinder, and harm others in terms of their 'differences' in color. With racism plaguing America like an incurable cancer, the so-called 'Christian' white American heart should be more receptive to a proven solution to such a destructive problem. Perhaps it could be in time to save America from imminent disaster—the same destruction brought upon Germany by racism that eventually destroyed the Germans themselves.

* Each hour here in the Holy Land enables me to have greater spiritual insights into what is happening in America between black and white. The American Negro never can be blamed for his racial animosities—he is only reacting to four hundred years of the conscious racism of the American whites. But as racism leads America up the suicide path, I do believe, from the experiences that I have had with them, that the whites of the younger generation, in the colleges and universities, will see the handwriting on the wall and many of them will turn to the spiritual path of truth—the only way left to America to ward off the disaster that racism inevitably must lead to.

* All praise is due to Allah, the Lord of all the Worlds.

* I reflected many, many times to myself upon how the American Negro has been entirely brainwashed from ever seeing or thinking of himself, as he should, as a part of the non-white peoples of the world. The American Negro has no conception of the hundreds of millions of other non-whites' concern for him: he has no conception of their feeling of brotherhood for and with him.

* The American black "leader's" most critical problem is lack of imagination! His thinking, his strategies, if any, are always limited, at least basically, to only that which is either advised, or approved by the white man. And the first thing the American power structure doesn't want any Negroes to start is thinking internationally.

* In the past, yes, I have made sweeping indictments of all white people. I never will be guilty of that again—as I know now that some white people are truly sincere, that some truly are capable of being brotherly toward a black man. The true Islam has shown me that a blanket indictment of all white people is as wrong as when whites make blanket indictments against blacks. Yes, I have been convinced that some American whites do want to help cure the rampant racism which is on the path to destroying this country!

* Why, here in America, the seeds of racism are so deeply rooted in the white people collectively, their belief that they are 'superior' in some way is so deeply rooted, that these things are in the national white subconsciousness. Many whites are even actually unaware of their own racism, until they face some test, and then their racism emerges in one form or another.

* In Mecca, too, I had played back for myself the twelve years I had spent with Elijah Muhammad as if it were a motion picture. I guess it would be impossible for anyone ever to realize fully how complete was my belief in Elijah Muhammad. I believed in him not only as a leader in the ordinary human sense, but also I believed in him as a divine leader, I believed he had no human weaknesses or faults, and that, therefore, he could make no mistakes and that he could do no wrong. There on a Holy World hilltop, I realized how very dangerous it is for people to hold any human being in such esteem, especially to consider anyone some sort of "divinely guided" and "protected" person.

* "I've had enough of someone else's propaganda," I had written to these friends. "I'm for truth, no matter who tells it. I'm for justice, no matter who it is for or against. I'm a human being first and foremost, and as such I'm for whoever and whatever benefits humanity as a whole."

* It takes no one to stir up the sociological dynamite that stems from the unemployment, bad housing, and inferior education already in the ghettoes. This explosively criminal condition has existed for so long, it needs no fuse; it fuses itself; it spontaneously combusts from within itself...

* They called me "the angriest Negro in America." I wouldn't deny that charge. I spoke exactly as I felt. "I believe in anger. The Bible says there is a time for anger." They called me "a teacher, a fomentor of violence." I would say point blank, "That is a lie. I'm not for wanton violence, I'm for justice. I feel that if white people were attacked by Negroes—if the forces of law prove unable, or inadequate, or reluctant to protect those whites from those Negroes—then those white people should protect and defend themselves from those Negroes, using arms if necessary. And I feel that when the law fails to protect Negroes from whites' attack, then those Negroes should use arms, if necessary, to defend themselves."

* "Malcolm X Advocates Armed Negroes!"What was wrong with that? I'll tell you what was wrong. I was a black man talking about physical defense against the white man. The white man can lynch and burn and bomb and beat Negroe —that's all right: "Have patience"..."The customs are entrenched"..."Things are getting better."

* Well, I believe it's a crime for anyone who is being brutalized to continue to accept that brutality without doing something to defend himself. If that's how "Christian" philosophy is interpreted, if that's what Gandhian philosophy teaches, well, then, I will call them criminal philosophies.

* I tried in every speech I made to clarify my new position regarding white people—"I don't speak against the sincere, well-meaning, good white people. I have learned that there are some. I have learned that not all white people are racists. I am speaking against and my fight is against the white racists. I firmly believe that Negroes have the right to fight against these racists, by any means that are necessary."

* "I am for violence if non-violence means we continue postponing a solution to the American black man's problem—just to avoid violence. I don't go for non-violence if it also means a delayed solution. To me a delayed solution is a non-solution. Or I'll say it another way. If it must take violence to get the black man his human rights in this country, I'm for violence exactly as you know the Irish, the Poles, or Jews would be if they were flagrantly discriminated against. I am just as they would be in that case, and they would be for violence—no matter what the consequences, no matter who was hurt by the violence.

* White society hates to hear anybody, especially a black man, talk about the crime the white man has perpetrated on the black man. I have always understood that's why I have been so frequently called "a revolutionist." It sounds as if I have done some crime! Well, it may be the American black man does need to become involved in a real revolution. The word for "revolution" in German is Umwälzung. What it means is a complete overturn—a complete change.

* When the white man came into this country, he certainly wasn't demonstrating any "non violence." In fact, the very man whose name symbolizes non-violence here today has stated:  "Our nation was born in genocide when it embraced the doctrine that the original American, the Indian, was an inferior race. Even before there were large numbers of Negroes on our shores, the scar of racial hatred had already disfigured colonial society. From the sixteenth centuryforward, blood flowed in battles over racial supremacy. We are perhaps the only nation which tried as a matter of national policy to wipe out its indigenous population. Moreover, we elevated that tragic experience into a noble crusade. Indeed, even today we have not permitted ourselves to reject or to feel remorse for this shameful episode. Our literature, our films, our drama, our folklore all exalt it. Our children are still taught to respect the violence which reduced a red skinned people of an earlier culture into a few fragmented groups herded into impoverished reservations."

* "Peaceful coexistence!" That's another one the white man has always been quick to cry. Fine! But what have been the deeds of the white man? During his entire advance through history, he has been waving the banner of Christianity...and carrying in his other hand the sword and the flintlock.  You can go right back to the very beginning of Christianity. Catholicism, the genesis of Christianity as we know it to be presently constituted, with its hierarchy, was conceived in Afric —by those whom the Christian church calls "The Desert Fathers." The Christian church became infected with racism when it entered white Europe. The Christian church returned to Africa under the banner of the Cross—conquering, killing, exploiting, pillaging, raping, bullying, beating—and teaching white supremacy. This is how the white man thrust himself into the position of leadership of the world—through the use of naked physical power. And he was totally inadequate spiritually. Mankind's history has proved from one era to another that the true criterion of leadership is spiritual. Men are attracted by spirit. By power, men are forced. Love is engendered by spirit. By power, anxieties are created.

* I am in agreement one hundred percent with those racists who say that no government laws ever can force brotherhood. The only true world solution today is governments guided by true religion—of the spirit. Here in race-torn America, I am convinced that the Islam religion is desperately needed, particularly by the American black man. The black man needs to reflect that he has been America's most fervent Christian—and where has it gotten him? In fact, in the white man's hands, in the white man's interpretation...where has Christianity brought this world?

* Well, if this is so—if the so-called "Christianity" now being practiced in America displays the best that world Christianity has left to offer—no one in his right mind should need any much greater proof that very close at hand is the end of Christianity.

* And what is the greatest single reason for this Christian church's failure? It is its failure to combat racism. It is the old "You sow, you reap" story. The Christian church sowed racism blasphemously; now it reaps racism.

* I believe that God now is giving the world's so-called "Christian" white society its last opportunity to repent and atone for the crimes of exploiting and enslaving the world's non-white peoples. It is exactly as when God gave Pharaoh a chance to repent. But Pharaoh persisted in his refusal to give justice to those whom he oppressed. And, we know, God finally destroyed Pharaoh.  Is white America really sorry for her crimes against the black people? Does white America have the capacity to repent—and to atone? Does the capacity to repent, to atone, exist in a majority, in one-half, in even one-third of American white society?  Many black men, the victims—in fact most black men—would like to be able to forgive, to forget, the crimes.  But most American white people seem not to have it in them to make any serious atonement—to do justice to the black man.

* Indeed, how can white society atone for enslaving, for raping, for unmanning, for otherwise brutalizing millions of human beings, for centuries? What atonement would the God of Justice demand for the robbery of the black people's labor, their lives, their true identities, their culture, their history—and even their human dignity?

* I told him, "What you are telling me is that it isn't the American white man who is a racist, but it's the American political, economic, and social atmosphere that automatically nourishes a racist psychology in the white man." He agreed.  We both agreed that American society makes it next to impossible for humans to meet in America and not be conscious of their color differences. And we both agreed that if racism could be removed, America could offer a society where rich and poor could truly live like human beings.

* That discussion with the ambassador gave me a new insight—one which I like: that the white man is not inherently evil, but America's racist society influences him to act evilly. The society has produced and nourishes a psychology which brings out the lowest, most base part of human beings.

* I just got up from my breakfast one morning and walked over to where he was and I told him I knew he was following me, and if he wanted to know anything, why didn't he ask me. He started to give me one of those too-lofty-to-descend-to-you attitudes. I told him then right to his face he was a fool, that he didn't know me, or what I stood for, so that made him one of those people who let somebody else do their thinking; and that no matter what job a man had, at least he ought to be able to think for himself. That stung him; he let me have it.

* I was, to hear him tell it, anti-American, un-American, seditious, subversive, and probably Communist. I told him that what he said only proved how little he understood about me. I told him that the only thing the F.B.I, the C.I.A., or anybody else could ever find me guilty of, was being open-minded. I said I was seeking for the truth, and I was trying to weigh—objectivelyeverything on its own merit. I said what I was against was strait-jacketed thinking, and strait jacketed societies. I said I respected every man's right to believe whatever his intelligence tells him is intellectually sound, and I expect everyone else to respect my right to believe likewise.

* And an even clearer proof for me of how Jews truly regard Negroes, I said, was what invariably happened wherever a Negro moved into any white residential neighborhood that was thickly Jewish. Who would always lead the whites' exodus? The Jews! Generally in these situations, some whites stay put—you just notice who they are: they're Irish Catholics, they're Italians; they're rarely ever any Jews. And, ironically, the Jews themselves often still have trouble being "accepted."  Saying this, I know I'll hear "anti-Semitic" from every direction again. Oh, yes! But truth is truth.

* I said I felt that as far as the American black man was concerned they were both just about the same. I felt that it was for the black man only a question of Johnson, the fox, or Goldwater, the wolf."Conservatism" in America's politics means "Let's keep the niggers in their place." And "liberalism" means "Let's keep the knee-grows in their place—but tell them we'll treat them a little better; let's fool them more, with more promises." With these choices, I felt that the American black man only needed to choose which one to be eaten by, the "liberal" fox or the "conservative" wolf—because both of them would eat him.

* I didn't go for Goldwater any more than for Johnson—except that in a wolf's den, I'd always known exactly where I stood; I'd watch the dangerous wolf closer than I would the smooth, sly fox. The wolf's very growling would keep me alert and fighting him to survive, whereas I might be lulled and fooled by the tricky fox. I'll give you an illustration of the fox. When the assassination in Dallas made Johnson President, who was the first person he called for? It was for his best friend, "Dicky"—Richard Russell of Georgia. Civil rights was "a moral issue," Johnson was declaring to everybody—while his best friend was the Southern racist who led the civil rights opposition. How would some sheriff sound, declaring himself so against bank robbery—and Jesse James his best friend?

* Goldwater as a man, I respected for speaking out his true convictions—something rarely done in politics today. He wasn't whispering to racists and smiling at integrationists. I felt Goldwater wouldn't have risked his unpopular stand without conviction. He flatly told black men he wasn't for them—and there is this to consider: always, the black people have advanced further when they have seen they had to rise up against a system that they clearly saw was outright against them. Under the steady lullabies sung by foxy liberals, the Northern Negro became a beggar. But the Southern Negro, facing the honestly snarling white man, rose up to battle that white man for his freedom—long before it happened in the North.

* I was no less angry than I had been, but at the same time the true brotherhood I had seen in the Holy World had influenced me to recognize that anger can blind human vision.

* Since I learned the truth in Mecca, my dearest friends have come to include all kinds—some Christians, Jews, Buddhists, Hindus, agnostics, and even atheists! I have friends who are called Capitalists, Socialists, and Communists! Some of my friends are moderates, conservatives, extremists—some are even Uncle Toms! My friends today are black, brown, red, yellow, and white!

* I said to Harlem street audiences that only when mankind would submit to the One God who created all—only then would mankind even approach the "peace" of which so much talk could be heard...but toward which so little action was seen.

* When I say that here now, it makes me think about that little co-ed I told you about, the one who flew from her New England college down to New York and came up to me in the Nation of Islam's restaurant in Harlem, and I told her that there was "nothing" she could do. I regret that I told her that. I wish that now I knew her name, or where I could telephone her, or write to her, and tell her what I tell white people now when they present themselves as being sincere, and ask me, one way or another, the same thing that she asked.

* The first thing I tell them is that at least where my own particular Black Nationalist organization, the Organization of Afro-American Unity, is concerned, they can't join us. I have these very deep feelings that white people who want to join black organizations are really just taking the escapist way to salve their consciences. By visibly hovering near us, they are "proving" that they are "withus." But the hard truth is this isn't helping to solve America's racist problem. The Negroes aren't the racists. Where the really sincere white people have got to do their "proving" of themselves is not among the black victims, but out on the battle lines of where America's racism really is—and that's in their own home communities; America's racism is among their own fellow whites. That's where the sincere whites who really mean to accomplish something have got to work.

* Let sincere whites go and teach non-violence to white people!

* Sometimes, I have dared to dream to myself that one day, history may even say that my voice which disturbed the white man's smugness, and his arrogance, and his complacency—that myvoice helped to save America from a grave, possibly even a fatal catastrophe.

* No man is given but so much time to accomplish whatever is his life's work.

* I am only facing the facts when I know that any moment of any day, or any night, could bring me death.

* To speculate about dying doesn't disturb me as it might some people. I never have felt that I would live to become an old man. Even before I was a Muslim—when I was a hustler in the ghetto jungle, and then a criminal in prison, it always stayed on my mind that I would die a violent death. In fact, it runs in my family. My father and most of his brothers died by violence my father because of what he believed in. To come right down to it, if I take the kind of things in which I believe, then add to that the kind of temperament that I have, plus the one hundred percent dedication I have to whatever I believe in—these are ingredients which make it just about impossible for me to die of old age.

* I have given to this book so much of whatever time I have because I feel, and I hope, that if I honestly and fully tell my life's account, read objectively it might prove to be a testimony of some social value.

* I think that an objective reader may see how in the society to which I was exposed as a black youth here in America, for me to wind up in a prison was really just about inevitable. It happens to so many thousands of black youth.

* The F.B.I. not long ago released a report of a shocking rise in crime each successive year since the end of World War II ten to twelve percent each year. The report did not say so in so many words, but I am saying that the majority of that crime increase is annually spawned in the black ghettoes which the American racist society permits to exist.

* But it is only after the deepest darkness that the greatest joy can come; it is only after slavery and prison that the sweetest appreciation of freedom can come.

* Aside from the basic African dialects, I would try to learn Chinese, because it looks as if Chinese will be the most powerful political language of the future. And already I have begun studying Arabic, which I think is going to be the most powerful spiritual language of the future.

* Those who would hunt a man need to remember that a jungle also contains those who hunt the hunters.

* Anyway, now, each day I live as if I am already dead, and I tell you what I would like for you to do. When I am dead—I say it that way because from the things I know, I do not expect to live long enough to read this book in its finished form—I want you to just watch and see if I'm not right in what I say: that the white man, in his press, is going to identify me with "hate."

* He will make use of me dead, as he has made use of me alive, as a convenient symbol of "hatred"—and that will help him to escape facing the truth that all I have been doing is holding up a mirror to reflect, to show, the history of unspeakable crimes that his race has committed against my race.

* And since I have been some kind of a "leader" of black people here in the racist society of America, I have been more reassured each time the white man resisted me, or attacked me harder—because each time made me more certain that I was on the right track in the American black man's best interests. The racist white man's opposition automatically made me know that I did offer the black man something worthwhile.

* Yes, I have cherished my "demagogue" role. I know that societies often have killed the people who have helped to change those societies. And if I can die having brought any light, having exposed any meaningful truth that will help to destroy the racist cancer that is malignant in the body of America—then, all of the credit is due to Allah. Only the mistakes have been mine.

=== Epilogue

* I have less patience with someone who doesn't wear a watch than with anyone else, for this type is not time-conscious.

* In all our deeds, the proper value and respect for time determines success or failure.

* Coffee is the only thing I like integrated.

* I had heard him bitterly attack other Negro writers as "Uncle Toms," "yard Negroes," "black men in white clothes."

* For perhaps a month I was afraid we weren't going to get any book. Malcolm X was still stiffly addressing me as "Sir!" and my notebook contained almost nothing but Black Muslim philosophy, praise of Mr. Muhammad, and the "evils" of "the white devil."

* I began leaving two white paper napkins by him every time I served him more coffee, and the ruse worked when he sometimes scribbled on the napkins, which I retrieved when he left. Some examples are these:"Here lies a YM, killed by a BM, fighting for the WM, who killed all the RM." (Decoding that wasn't difficult knowing Malcolm X. "YM" was for yellow man, "BM" for black man, "WM" for white man, and "RM" was for red man.)  "Nothing ever happened without cause. Cause BM condition WM won't face. WM obsessed with hiding his guilt."  "If Christianity had asserted itself in Germany, six million Jews would have lived."  "WM so quick to tell BM 'Look what I have done for you!' No! Look what you have done to us!"  "BM dealing with WM who put our eyes out, now he condemns us because we cannot see."  "Only persons really changed history those who changed men's thinking about themselves. Hitler as well as Jesus, Stalin as well as Buddha...Hon. Elijah Muhammad...."

* Malcolm X looked squarely at me. "You I trust about twenty-five percent."

* "The only thing I considered wrong was what I got caught doing wrong. I had a jungle mind, I was living in a jungle, and everything I did was done by instinct to survive." But he stressed that he had no regrets about his crimes, "because it was all a result of what happens to thousands upon thousands of black men in the white man's Christian world."

* Learn wisdom from the pupil of the eye that looks upon all things and yet to self is blind. Persian poet.

* "It made me face something about myself," Malcolm X said. "My mind had closed about our mother. I simply didn't feel the problem could be solved, so I had shut it out. I had built up subconscious defenses. The white man does this. He shuts out of his mind, and he builds up subconscious defenses against anything he doesn't want to face up to. I've just become aware how closed my mind was now that I've opened it up again. That's one of the characteristics I don't like about myself. If I meet a problem I feel I can't solve, I shut it out. I make believe that it doesn't exist. But it exists."

* Yes, I'm an extremist. The black race here in North America is in extremely bad condition. You show me a black man who isn't an extremist and I'll show you one who needs psychiatric attention!"

* Malcolm speaking in Harlem stared down at one of the white reporters present, the only whites admitted to the meeting, and went on, 'Now, there's a reporter who hasn't taken a note in half an hour, but as soon as I start talking about the Jews, he's busy taking notes to prove that I'm anti Semitic'

* Children have a lesson adults should learn, to not be ashamed of failing, but to get up and try again. Most of us adults are so afraid, so cautious, so 'safe,' and therefore so shrinking and rigid and afraid that it is why so many humans fail. Most middle-aged adults have resigned themselves to failure.

* Only the unasked question is stupid

* why I have been able to have some effect is because I make a study of the weaknesses of this country and because the more the white man yelps, the more I know I have struck a nerve.

* You know this place here in this chapter where I told you how I put the pistol up to my head and kept pulling the trigger and scared them so when I was starting the burglary ring -well... I don't know if I ought to tell you this or not, but I want to tell the truth. I palmed the bullet.

* Whether you use bullets or ballots, you've got to aim well; don't strike at the puppet, strike at the puppeteer.

* Could any whites join his OAAU? "If John Brown were alive, maybe him."

* And he answered his critics with such statements as that he would send "armed guerrillas" into Mississippi. "I am dead serious. We will send them not only to Mississippi, but to any place where black people's lives are threatened by white bigots. As far as I am concerned, Mississippi is anywhere south of theCanadian border."

* At another time, when Evelyn Cunningham of the Pittsburgh Courier asked Malcolm X in a kidding way, "Say something startling for my column," he told her, "Anyone who wants to follow me and my movement has got to be ready to go to jail, to the hospital, and to the cemetery before he can be truly free." Evelyn Cunningham, printing the item, commented, "He smiled and chuckled, but he was in dead earnest."

* "I believe in recognizing every human being as a human being—neither white, black, brown, or red; and when you are dealing with humanity as a family there's no question of integration or intermarriage. It's just one human being marrying another human being or one human being living around and with another human being. I may say, though, that I don't think it should ever be put upon a black man, I don't think the burden to defend any position should ever be put upon the black man, because it is the white man collectively who has shown that he is hostile toward integration and toward intermarriage and toward these other strides toward oneness. So as a black man and especially as a black American, any stand that I formerly took, I don't thinkthat I would have to defend it because it's still a reaction to the society, and it's a reaction that was produced by the society; and I think that it is the society that produced this that should be attacked, not the reaction that develops among the people who are the victims of that negative society.

* Returned to New York City, Malcolm X soon flew to France. He was scheduled to speak before a Congress of African Students. But he was formally advised that he would not be permitted to speak and, moreover, that he could consider himself officially barred forever from France as "an undesirable person." He was asked to leave—and he did, fuming with indignation.

* I did many things as a Muslim that I'm sorry for now. I was a zombie then—like all Muslims—I was hypnotized, pointed in a certain direction and told to march. Well, I guess a man's entitled to make a fool of himself if he's ready to pay the cost. It cost me twelve years.

* But, you know, I'm going to tell you something, brothe —the more I keep thinking about this thing, the things that have been happening lately, I'm not all that sure it's the Muslims. I know what they can do, and what they can't, and they can't do some of the stuff recently going on. Now, I'm going to tell you, the more I keep thinking about what happened to me in France, I think I'm going to quit saying it's the Muslims.

* He stood up and paced about the little room. He said he was going to state that he had been hasty to accuse the Black Muslims of bombing his home. "Things have happened since that are bigger than what they can do. I know what they can do. Things have gone beyond that."

* The Reverend Galamison and other notables due hadn't arrived by three o'clock. "Brother Malcolm looked so disappointed," the young lady says. "He said to me 'I don't think any of them are coming, either.' I felt so terrible for him. It did seem as if no one cared.  (It was also reported by another source that Galamison, unable to come to the meeting, did telephone earlier, and that Malcolm X was told of this before he went out to speak.)

* Malcolm X turned and looked back at his young lady assistant. "You'll have to forgive me for raising my voice to you—I'm just about at my wit's end."  "Oh, don't mention it!" she said quickly, "I understand." His voice sounded far away, “I wonder if anybody really understands—” And he walked out onto the stage
